(let [kll-header "resources/kll-header.txt"
      layout "resources/ergodox-keymap.edn"]
  (make-kll-file-bodies kll-header layout))
=>
{:exploded [{:hand :left,
             :section :thumb,
             :position [0 0],
             :layer 0,
             :shortcut :lctrl}
            {:hand :left,
             :section :thumb,
             :position [1 0],
             :layer 0,
             :shortcut :lalt}
            {:hand :left,
             :section :thumb,
             :position [1 2],
             :layer 0,
             :shortcut :lshift}
            {:hand :left,
             :section :thumb,
             :position [2 0],
             :layer 0,
             :shortcut :escape}
            {:hand :left,
             :section :thumb,
             :position [2 1],
             :layer 0,
             :shortcut :lgui}
            {:hand :left,
             :section :thumb,
             :position [2 1],
             :layer 1,
             :shortcut :app}
            {:hand :left,
             :section :thumb,
             :position [2 2],
             :layer 0,
             :shortcut :space}
            {:hand :left,
             :section :fingers,
             :position [4 3],
             :layer 0,
             :shortcut :p}
            {:hand :left,
             :section :fingers,
             :position [2 2],
             :layer 0,
             :shortcut :o}
            {:hand :left,
             :section :fingers,
             :position [2 2],
             :layer 1,
             :shortcut :cursive/shrink-selection}
            {:hand :left,
             :section :fingers,
             :position [0 0],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [1 0],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [2 3],
             :layer 0,
             :shortcut :l}
            {:hand :left,
             :section :fingers,
             :position [2 3],
             :layer 1,
             :shortcut :cursive/load-file-in-repl}
            {:hand :left,
             :section :fingers,
             :position [3 3],
             :layer 0,
             :shortcut :a}
            {:hand :left,
             :section :fingers,
             :position [3 3],
             :layer 1,
             :shortcut :cursive/switch-repl-to-ns}
            {:hand :left,
             :section :fingers,
             :position [5 4],
             :layer 0,
             :shortcut :5}
            {:hand :left,
             :section :fingers,
             :position [5 4],
             :layer 1,
             :shortcut :f5}
            {:hand :left,
             :section :fingers,
             :position [5 4],
             :layer 3,
             :shortcut :f5}
            {:hand :left,
             :section :fingers,
             :position [5 4],
             :layer 4,
             :shortcut :f15}
            {:hand :left,
             :section :fingers,
             :position [1 1],
             :layer 0,
             :shortcut :backslash}
            {:hand :left,
             :section :fingers,
             :position [6 3],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [3 4],
             :layer 0,
             :shortcut :3}
            {:hand :left,
             :section :fingers,
             :position [3 4],
             :layer 1,
             :shortcut :f3}
            {:hand :left,
             :section :fingers,
             :position [3 4],
             :layer 3,
             :shortcut :f3}
            {:hand :left,
             :section :fingers,
             :position [3 4],
             :layer 4,
             :shortcut :f13}
            {:hand :left,
             :section :fingers,
             :position [4 2],
             :layer 0,
             :shortcut :u}
            {:hand :left,
             :section :fingers,
             :position [3 0],
             :layer 0,
             :shortcut :k}
            {:hand :left,
             :section :fingers,
             :position [3 0],
             :layer 2,
             :shortcut :cursive/kill-sexp}
            {:hand :left,
             :section :fingers,
             :position [5 3],
             :layer 0,
             :shortcut :y}
            {:hand :left,
             :section :fingers,
             :position [4 1],
             :layer 0,
             :shortcut :fun1}
            {:hand :left,
             :section :fingers,
             :position [4 1],
             :layer 2,
             :shortcut :cursive/send-top-form-to-repl}
            {:hand :left,
             :section :fingers,
             :position [5 2],
             :layer 0,
             :shortcut :i}
            {:hand :left,
             :section :fingers,
             :position [1 4],
             :layer 0,
             :shortcut :1}
            {:hand :left,
             :section :fingers,
             :position [1 4],
             :layer 1,
             :shortcut :f1}
            {:hand :left,
             :section :fingers,
             :position [1 4],
             :layer 3,
             :shortcut :f1}
            {:hand :left,
             :section :fingers,
             :position [1 4],
             :layer 4,
             :shortcut :f12}
            {:hand :left,
             :section :fingers,
             :position [1 3],
             :layer 0,
             :shortcut :tab}
            {:hand :left,
             :section :fingers,
             :position [6 4],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [0 3],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [5 1],
             :layer 0,
             :shortcut :x}
            {:hand :left,
             :section :fingers,
             :position [6 1],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [2 4],
             :layer 0,
             :shortcut :2}
            {:hand :left,
             :section :fingers,
             :position [2 4],
             :layer 1,
             :shortcut :f2}
            {:hand :left,
             :section :fingers,
             :position [2 4],
             :layer 3,
             :shortcut :f2}
            {:hand :left,
             :section :fingers,
             :position [2 4],
             :layer 4,
             :shortcut :f12}
            {:hand :left,
             :section :fingers,
             :position [0 2],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [2 0],
             :layer 0,
             :shortcut :q}
            {:hand :left,
             :section :fingers,
             :position [0 4],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [3 1],
             :layer 0,
             :shortcut :fun2}
            {:hand :left,
             :section :fingers,
             :position [3 1],
             :layer 1,
             :shortcut :cursive/send-top-form-to-repl}
            {:hand :left,
             :section :fingers,
             :position [2 1],
             :layer 0,
             :shortcut :j}
            {:hand :left,
             :section :fingers,
             :position [2 1],
             :layer 1,
             :shortcut :cursive/send-form-before-to-repl}
            {:hand :left,
             :section :fingers,
             :position [4 4],
             :layer 0,
             :shortcut :4}
            {:hand :left,
             :section :fingers,
             :position [4 4],
             :layer 1,
             :shortcut :f4}
            {:hand :left,
             :section :fingers,
             :position [4 4],
             :layer 3,
             :shortcut :f4}
            {:hand :left,
             :section :fingers,
             :position [4 4],
             :layer 4,
             :shortcut :f14}
            {:hand :left,
             :section :fingers,
             :position [1 2],
             :layer 0,
             :shortcut :delete}
            {:hand :left,
             :section :fingers,
             :position [3 2],
             :layer 0,
             :shortcut :e}
            {:hand :left,
             :section :fingers,
             :position [3 2],
             :layer 1,
             :shortcut :cursive/extend-selection}
            {:hand :left,
             :section :fingers,
             :position [0 1],
             :layer 0,
             :shortcut nil}
            {:hand :left,
             :section :fingers,
             :position [4 0],
             :layer 0,
             :shortcut :s}
            {:hand :left,
             :section :fingers,
             :position [4 0],
             :layer 2,
             :shortcut :cursive/split-sexp}
            {:hand :right,
             :section :thumb,
             :position [0 0],
             :layer 0,
             :shortcut :space}
            {:hand :right,
             :section :thumb,
             :position [1 0],
             :layer 0,
             :shortcut :rshift}
            {:hand :right,
             :section :thumb,
             :position [1 2],
             :layer 0,
             :shortcut :ralt}
            {:hand :right,
             :section :thumb,
             :position [2 0],
             :layer 0,
             :shortcut :escape}
            {:hand :right,
             :section :thumb,
             :position [2 1],
             :layer 0,
             :shortcut :rgui}
            {:hand :right,
             :section :thumb,
             :position [2 1],
             :layer 1,
             :shortcut :app}
            {:hand :right,
             :section :thumb,
             :position [2 2],
             :layer 0,
             :shortcut :ralt}
            {:hand :right,
             :section :fingers,
             :position [4 3],
             :layer 0,
             :shortcut :g}
            {:hand :right,
             :section :fingers,
             :position [4 3],
             :layer 2,
             :shortcut :home}
            {:hand :right,
             :section :fingers,
             :position [2 2],
             :layer 0,
             :shortcut :n}
            {:hand :right,
             :section :fingers,
             :position [2 2],
             :layer 2,
             :shortcut :right}
            {:hand :right,
             :section :fingers,
             :position [2 2],
             :layer 3,
             :shortcut :rbracket}
            {:hand :right,
             :section :fingers,
             :position [2 2],
             :layer 4,
             :shortcut :question-mark}
            {:hand :right,
             :section :fingers,
             :position [0 0],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 0,
             :shortcut :z}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 1,
             :shortcut :lat1}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 2,
             :shortcut :lat2}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 3,
             :shortcut :lat3}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 4,
             :shortcut :lat4}
            {:hand :right,
             :section :fingers,
             :position [1 0],
             :layer 5,
             :shortcut :lat5}
            {:hand :right,
             :section :fingers,
             :position [2 3],
             :layer 0,
             :shortcut :r}
            {:hand :right,
             :section :fingers,
             :position [2 3],
             :layer 1,
             :shortcut :cursive/raise-form}
            {:hand :right,
             :section :fingers,
             :position [2 3],
             :layer 2,
             :shortcut :end}
            {:hand :right,
             :section :fingers,
             :position [2 3],
             :layer 3,
             :shortcut :right-curly-brace}
            {:hand :right,
             :section :fingers,
             :position [3 3],
             :layer 0,
             :shortcut :c}
            {:hand :right,
             :section :fingers,
             :position [3 3],
             :layer 1,
             :shortcut :cursive/move-form-up}
            {:hand :right,
             :section :fingers,
             :position [3 3],
             :layer 2,
             :shortcut :up}
            {:hand :right,
             :section :fingers,
             :position [3 3],
             :layer 3,
             :shortcut :left-curly-brace}
            {:hand :right,
             :section :fingers,
             :position [5 4],
             :layer 0,
             :shortcut :6}
            {:hand :right,
             :section :fingers,
             :position [5 4],
             :layer 1,
             :shortcut :f6}
            {:hand :right,
             :section :fingers,
             :position [1 1],
             :layer 0,
             :shortcut :enter}
            {:hand :right,
             :section :fingers,
             :position [1 1],
             :layer 3,
             :shortcut :cursive/wrap-with-round-braces}
            {:hand :right,
             :section :fingers,
             :position [6 3],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [3 4],
             :layer 0,
             :shortcut :8}
            {:hand :right,
             :section :fingers,
             :position [3 4],
             :layer 1,
             :shortcut :f8}
            {:hand :right,
             :section :fingers,
             :position [3 4],
             :layer 3,
             :shortcut :clj/thread-first-backwards}
            {:hand :right,
             :section :fingers,
             :position [4 2],
             :layer 0,
             :shortcut :h}
            {:hand :right,
             :section :fingers,
             :position [4 2],
             :layer 2,
             :shortcut :left}
            {:hand :right,
             :section :fingers,
             :position [4 2],
             :layer 3,
             :shortcut :cursive/wrap-with-double-quotes}
            {:hand :right,
             :section :fingers,
             :position [4 2],
             :layer 4,
             :shortcut :equals}
            {:hand :right,
             :section :fingers,
             :position [4 2],
             :layer 5,
             :shortcut :double-quote}
            {:hand :right,
             :section :fingers,
             :position [3 0],
             :layer 0,
             :shortcut :w}
            {:hand :right,
             :section :fingers,
             :position [3 0],
             :layer 1,
             :shortcut :cursive/join-sexp}
            {:hand :right,
             :section :fingers,
             :position [3 0],
             :layer 2,
             :shortcut :cursive/sexp-down-right}
            {:hand :right,
             :section :fingers,
             :position [3 0],
             :layer 3,
             :shortcut :left-angle-brace}
            {:hand :right,
             :section :fingers,
             :position [3 0],
             :layer 5,
             :shortcut :comma}
            {:hand :right,
             :section :fingers,
             :position [5 3],
             :layer 0,
             :shortcut :f}
            {:hand :right,
             :section :fingers,
             :position [5 3],
             :layer 2,
             :shortcut :pageup}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 0,
             :shortcut :fun3}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 1,
             :shortcut :cursive/slurp-forward}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 2,
             :shortcut :cursive/sexp-down-left}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 3,
             :shortcut :fun3}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 4,
             :shortcut :minus}
            {:hand :right,
             :section :fingers,
             :position [4 1],
             :layer 5,
             :shortcut :colon}
            {:hand :right,
             :section :fingers,
             :position [5 2],
             :layer 0,
             :shortcut :d}
            {:hand :right,
             :section :fingers,
             :position [5 2],
             :layer 2,
             :shortcut :previous-word}
            {:hand :right,
             :section :fingers,
             :position [5 2],
             :layer 5,
             :shortcut :backtick}
            {:hand :right,
             :section :fingers,
             :position [1 4],
             :layer 0,
             :shortcut :0}
            {:hand :right,
             :section :fingers,
             :position [1 4],
             :layer 1,
             :shortcut :f10}
            {:hand :right,
             :section :fingers,
             :position [1 4],
             :layer 3,
             :shortcut :clj/thread-last}
            {:hand :right,
             :section :fingers,
             :position [1 3],
             :layer 0,
             :shortcut :backspace}
            {:hand :right,
             :section :fingers,
             :position [1 3],
             :layer 2,
             :shortcut :pagedown}
            {:hand :right,
             :section :fingers,
             :position [1 3],
             :layer 3,
             :shortcut :cursive/wrap-with-curly-braces}
            {:hand :right,
             :section :fingers,
             :position [6 4],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [0 3],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [5 1],
             :layer 0,
             :shortcut :b}
            {:hand :right,
             :section :fingers,
             :position [5 1],
             :layer 5,
             :shortcut :tilde}
            {:hand :right,
             :section :fingers,
             :position [6 1],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [2 4],
             :layer 0,
             :shortcut :9}
            {:hand :right,
             :section :fingers,
             :position [2 4],
             :layer 1,
             :shortcut :f9}
            {:hand :right,
             :section :fingers,
             :position [2 4],
             :layer 3,
             :shortcut :clj/thread-first}
            {:hand :right,
             :section :fingers,
             :position [0 2],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [2 0],
             :layer 0,
             :shortcut :v}
            {:hand :right,
             :section :fingers,
             :position [2 0],
             :layer 2,
             :shortcut :cursive/sexp-right}
            {:hand :right,
             :section :fingers,
             :position [2 0],
             :layer 3,
             :shortcut :right-angle-brace}
            {:hand :right,
             :section :fingers,
             :position [2 0],
             :layer 4,
             :shortcut :backslash}
            {:hand :right,
             :section :fingers,
             :position [0 4],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 0,
             :shortcut :fun4}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 1,
             :shortcut :cursive/splice-sexp}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 2,
             :shortcut :cursive/sexp-up-left}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 3,
             :shortcut :left-round-brace}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 4,
             :shortcut :fun4}
            {:hand :right,
             :section :fingers,
             :position [3 1],
             :layer 5,
             :shortcut :period}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 0,
             :shortcut :fun5}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 1,
             :shortcut :cursive/barf-forward}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 2,
             :shortcut :cursive/sexp-up-right}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 3,
             :shortcut :right-round-brace}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 4,
             :shortcut :slash}
            {:hand :right,
             :section :fingers,
             :position [2 1],
             :layer 5,
             :shortcut :fun5}
            {:hand :right,
             :section :fingers,
             :position [4 4],
             :layer 0,
             :shortcut :7}
            {:hand :right,
             :section :fingers,
             :position [4 4],
             :layer 1,
             :shortcut :f7}
            {:hand :right,
             :section :fingers,
             :position [4 4],
             :layer 3,
             :shortcut :clj/thread-last-backwards}
            {:hand :right,
             :section :fingers,
             :position [1 2],
             :layer 0,
             :shortcut :escape}
            {:hand :right,
             :section :fingers,
             :position [1 2],
             :layer 2,
             :shortcut :next-word}
            {:hand :right,
             :section :fingers,
             :position [1 2],
             :layer 3,
             :shortcut :cursive/wrap-with-square-braces}
            {:hand :right,
             :section :fingers,
             :position [3 2],
             :layer 0,
             :shortcut :t}
            {:hand :right,
             :section :fingers,
             :position [3 2],
             :layer 1,
             :shortcut :cursive/move-form-down}
            {:hand :right,
             :section :fingers,
             :position [3 2],
             :layer 2,
             :shortcut :down}
            {:hand :right,
             :section :fingers,
             :position [3 2],
             :layer 3,
             :shortcut :lbracket}
            {:hand :right,
             :section :fingers,
             :position [3 2],
             :layer 5,
             :shortcut :quote}
            {:hand :right,
             :section :fingers,
             :position [0 1],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :section :fingers,
             :position [4 0],
             :layer 0,
             :shortcut :m}
            {:hand :right,
             :section :fingers,
             :position [4 0],
             :layer 2,
             :shortcut :cursive/sexp-left}
            {:hand :right,
             :section :fingers,
             :position [4 0],
             :layer 3,
             :shortcut :underscore}
            {:hand :right,
             :section :fingers,
             :position [4 0],
             :layer 4,
             :shortcut :plus}
            {:hand :right,
             :section :fingers,
             :position [4 0],
             :layer 5,
             :shortcut :semicolon}],
 :shortcuts {:left-curly-brace "{",
             :question-mark "?",
             :cursive/send-form-before-to-repl #{:shift :ctrl :b},
             :cursive/sexp-up-right #{:alt :n :ctrl},
             :cursive/split-sexp #{:shift :alt :s},
             :left-angle-brace "<",
             :cursive/slurp-forward #{:shift :0 :ctrl},
             :cursive/sexp-left #{:alt :ctrl :b},
             :cursive/move-form-down #{:shift :down :ctrl},
             :cursive/load-file-in-repl #{:shift :ctrl :l},
             :cursive/join-sexp #{:shift :alt :j},
             :cursive/close-round-brace-and-newline #{:shift :alt :0},
             :cursive/sexp-down-left #{:alt :ctrl :p},
             :right-curly-brace "}",
             :firmware/flashmode ("flashMode"),
             :cursive/splice-sexp #{:alt :s},
             :right-angle-brace ">",
             :tilde "~",
             :left-round-brace "(",
             :double-quote "\"",
             :colon ":",
             :cursive/raise-form #{:r :alt},
             :cursive/send-top-form-to-repl #{:shift :ctrl :t},
             :cursive/wrap-with-double-quotes #{:shift :alt :quote},
             :clj/thread-last "->>",
             :right-round-brace ")",
             :cursive/wrap-with-round-braces #{:shift :alt :9},
             :clj/thread-last-backwards "<<-",
             :previous-word #{:ctrl :left},
             :cursive/switch-repl-to-ns #{:shift :n :ctrl},
             :cursive/move-form-up #{:shift :ctrl :up},
             :cursive/sexp-up-left #{:alt :ctrl :u},
             :clj/thread-first "->",
             :cursive/extend-selection #{:w :ctrl},
             :plus "+",
             :cursive/sexp-right #{:alt :ctrl :f},
             :cursive/wrap-with-square-braces #{:alt :lbracket},
             :cursive/wrap-with-curly-braces #{:shift :alt :lbracket},
             :underscore "_",
             :cursive/shrink-selection #{:shift :w :ctrl},
             :next-word #{:ctrl :right},
             :clj/thread-first-backwards "<-",
             :cursive/kill-sexp #{:alt :ctrl :k},
             :cursive/barf-forward #{:shift :ctrl :rbrace},
             :cursive/sexp-down-right #{:alt :ctrl :d}},
 :kll-indexes {:left {:thumb {[0 0] {0 :lctrl},
                              [1 0] {0 :lalt},
                              [1 2] {0 :lshift},
                              [2 0] {0 :escape},
                              [2 1] {0 :lgui, 1 :app},
                              [2 2] {0 :space}},
                      :fingers {[4 3] {0 :p},
                                [2 2] {0 :o, 1 :cursive/shrink-selection},
                                [0 0] {0 nil},
                                [1 0] {0 nil},
                                [2 3] {0 :l, 1 :cursive/load-file-in-repl},
                                [3 3] {0 :a, 1 :cursive/switch-repl-to-ns},
                                [5 4] {0 :5, 1 :f5, 3 :f5, 4 :f15},
                                [1 1] {0 :backslash},
                                [6 3] {0 nil},
                                [3 4] {0 :3, 1 :f3, 3 :f3, 4 :f13},
                                [4 2] {0 :u},
                                [3 0] {0 :k, 2 :cursive/kill-sexp},
                                [5 3] {0 :y},
                                [4 1] {0 :fun1,
                                       2 :cursive/send-top-form-to-repl},
                                [5 2] {0 :i},
                                [1 4] {0 :1, 1 :f1, 3 :f1, 4 :f12},
                                [1 3] {0 :tab},
                                [6 4] {0 nil},
                                [0 3] {0 nil},
                                [5 1] {0 :x},
                                [6 1] {0 nil},
                                [2 4] {0 :2, 1 :f2, 3 :f2, 4 :f12},
                                [0 2] {0 nil},
                                [2 0] {0 :q},
                                [0 4] {0 nil},
                                [3 1] {0 :fun2,
                                       1 :cursive/send-top-form-to-repl},
                                [2 1] {0 :j,
                                       1 :cursive/send-form-before-to-repl},
                                [4 4] {0 :4, 1 :f4, 3 :f4, 4 :f14},
                                [1 2] {0 :delete},
                                [3 2] {0 :e, 1 :cursive/extend-selection},
                                [0 1] {0 nil},
                                [4 0] {0 :s, 2 :cursive/split-sexp}}},
               :right {:thumb {[0 0] {0 :space},
                               [1 0] {0 :rshift},
                               [1 2] {0 :ralt},
                               [2 0] {0 :escape},
                               [2 1] {0 :rgui, 1 :app},
                               [2 2] {0 :ralt}},
                       :fingers {[4 3] {0 :g, 2 :home},
                                 [2 2] {0 :n,
                                        2 :right,
                                        3 :rbracket,
                                        4 :question-mark},
                                 [0 0] {0 nil},
                                 [1 0] {0 :z,
                                        1 :lat1,
                                        2 :lat2,
                                        3 :lat3,
                                        4 :lat4,
                                        5 :lat5},
                                 [2 3] {0 :r,
                                        1 :cursive/raise-form,
                                        2 :end,
                                        3 :right-curly-brace},
                                 [3 3] {0 :c,
                                        1 :cursive/move-form-up,
                                        2 :up,
                                        3 :left-curly-brace},
                                 [5 4] {0 :6, 1 :f6},
                                 [1 1] {0 :enter,
                                        3 :cursive/wrap-with-round-braces},
                                 [6 3] {0 nil},
                                 [3 4] {0 :8,
                                        1 :f8,
                                        3 :clj/thread-first-backwards},
                                 [4 2] {0 :h,
                                        2 :left,
                                        3 :cursive/wrap-with-double-quotes,
                                        4 :equals,
                                        5 :double-quote},
                                 [3 0] {0 :w,
                                        1 :cursive/join-sexp,
                                        2 :cursive/sexp-down-right,
                                        3 :left-angle-brace,
                                        5 :comma},
                                 [5 3] {0 :f, 2 :pageup},
                                 [4 1] {0 :fun3,
                                        1 :cursive/slurp-forward,
                                        2 :cursive/sexp-down-left,
                                        3 :fun3,
                                        4 :minus,
                                        5 :colon},
                                 [5 2] {0 :d, 2 :previous-word, 5 :backtick},
                                 [1 4] {0 :0, 1 :f10, 3 :clj/thread-last},
                                 [1 3] {0 :backspace,
                                        2 :pagedown,
                                        3 :cursive/wrap-with-curly-braces},
                                 [6 4] {0 nil},
                                 [0 3] {0 nil},
                                 [5 1] {0 :b, 5 :tilde},
                                 [6 1] {0 nil},
                                 [2 4] {0 :9, 1 :f9, 3 :clj/thread-first},
                                 [0 2] {0 nil},
                                 [2 0] {0 :v,
                                        2 :cursive/sexp-right,
                                        3 :right-angle-brace,
                                        4 :backslash},
                                 [0 4] {0 nil},
                                 [3 1] {0 :fun4,
                                        1 :cursive/splice-sexp,
                                        2 :cursive/sexp-up-left,
                                        3 :left-round-brace,
                                        4 :fun4,
                                        5 :period},
                                 [2 1] {0 :fun5,
                                        1 :cursive/barf-forward,
                                        2 :cursive/sexp-up-right,
                                        3 :right-round-brace,
                                        4 :slash,
                                        5 :fun5},
                                 [4 4] {0 :7,
                                        1 :f7,
                                        3 :clj/thread-last-backwards},
                                 [1 2] {0 :escape,
                                        2 :next-word,
                                        3 :cursive/wrap-with-square-braces},
                                 [3 2] {0 :t,
                                        1 :cursive/move-form-down,
                                        2 :down,
                                        3 :lbracket,
                                        5 :quote},
                                 [0 1] {0 nil},
                                 [4 0] {0 :m,
                                        2 :cursive/sexp-left,
                                        3 :underscore,
                                        4 :plus,
                                        5 :semicolon}}}},
 :xf [{:hand :left,
       :section :thumb,
       :position [0 0],
       :layer 0,
       :shortcut :lctrl,
       :kll-index {0 :lctrl},
       :kll-value "U\"LCTRL\";",
       :line-comment "left thumb [0 0]"}
      {:hand :left,
       :section :thumb,
       :position [1 0],
       :layer 0,
       :shortcut :lalt,
       :kll-index {0 :lalt},
       :kll-value "U\"LALT\";",
       :line-comment "left thumb [1 0]"}
      {:hand :left,
       :section :thumb,
       :position [1 2],
       :layer 0,
       :shortcut :lshift,
       :kll-index {0 :lshift},
       :kll-value "U\"LSHIFT\";",
       :line-comment "left thumb [1 2]"}
      {:hand :left,
       :section :thumb,
       :position [2 0],
       :layer 0,
       :shortcut :escape,
       :kll-index {0 :escape},
       :kll-value "U\"ESCAPE\";",
       :line-comment "left thumb [2 0]"}
      {:hand :left,
       :section :thumb,
       :position [2 1],
       :layer 0,
       :shortcut :lgui,
       :kll-index {0 :lgui, 1 :app},
       :kll-value "U\"LGUI\";",
       :line-comment "left thumb [2 1]"}
      {:hand :left,
       :section :thumb,
       :position [2 1],
       :layer 1,
       :shortcut :app,
       :kll-index {0 :lgui, 1 :app},
       :kll-value "U\"APP\";",
       :line-comment "left thumb [2 1]"}
      {:hand :left,
       :section :thumb,
       :position [2 2],
       :layer 0,
       :shortcut :space,
       :kll-index {0 :space},
       :kll-value "U\"SPACE\";",
       :line-comment "left thumb [2 2]"}
      {:hand :left,
       :section :fingers,
       :position [4 3],
       :layer 0,
       :shortcut :p,
       :kll-index {0 :p},
       :kll-value "U\"P\";",
       :line-comment "left fingers [4 3]"}
      {:hand :left,
       :section :fingers,
       :position [2 2],
       :layer 0,
       :shortcut :o,
       :kll-index {0 :o, 1 :cursive/shrink-selection},
       :kll-value "U\"O\";",
       :line-comment "left fingers [2 2]"}
      {:hand :left,
       :section :fingers,
       :position [2 2],
       :layer 1,
       :shortcut :cursive/shrink-selection,
       :kll-index {0 :o, 1 :cursive/shrink-selection},
       :kll-value "U\"SHIFT\" + U\"W\" + U\"CTRL\";",
       :line-comment "left fingers [2 2]"}
      {:hand :left,
       :section :fingers,
       :position [0 0],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [0 0]"}
      {:hand :left,
       :section :fingers,
       :position [1 0],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [1 0]"}
      {:hand :left,
       :section :fingers,
       :position [2 3],
       :layer 0,
       :shortcut :l,
       :kll-index {0 :l, 1 :cursive/load-file-in-repl},
       :kll-value "U\"L\";",
       :line-comment "left fingers [2 3]"}
      {:hand :left,
       :section :fingers,
       :position [2 3],
       :layer 1,
       :shortcut :cursive/load-file-in-repl,
       :kll-index {0 :l, 1 :cursive/load-file-in-repl},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"L\";",
       :line-comment "left fingers [2 3]"}
      {:hand :left,
       :section :fingers,
       :position [3 3],
       :layer 0,
       :shortcut :a,
       :kll-index {0 :a, 1 :cursive/switch-repl-to-ns},
       :kll-value "U\"A\";",
       :line-comment "left fingers [3 3]"}
      {:hand :left,
       :section :fingers,
       :position [3 3],
       :layer 1,
       :shortcut :cursive/switch-repl-to-ns,
       :kll-index {0 :a, 1 :cursive/switch-repl-to-ns},
       :kll-value "U\"SHIFT\" + U\"N\" + U\"CTRL\";",
       :line-comment "left fingers [3 3]"}
      {:hand :left,
       :section :fingers,
       :position [5 4],
       :layer 0,
       :shortcut :5,
       :kll-index {0 :5, 1 :f5, 3 :f5, 4 :f15},
       :kll-value "U\"5\";",
       :line-comment "left fingers [5 4]"}
      {:hand :left,
       :section :fingers,
       :position [5 4],
       :layer 1,
       :shortcut :f5,
       :kll-index {0 :5, 1 :f5, 3 :f5, 4 :f15},
       :kll-value "U\"F5\";",
       :line-comment "left fingers [5 4]"}
      {:hand :left,
       :section :fingers,
       :position [5 4],
       :layer 3,
       :shortcut :f5,
       :kll-index {0 :5, 1 :f5, 3 :f5, 4 :f15},
       :kll-value "U\"F5\";",
       :line-comment "left fingers [5 4]"}
      {:hand :left,
       :section :fingers,
       :position [5 4],
       :layer 4,
       :shortcut :f15,
       :kll-index {0 :5, 1 :f5, 3 :f5, 4 :f15},
       :kll-value "U\"F15\";",
       :line-comment "left fingers [5 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 1],
       :layer 0,
       :shortcut :backslash,
       :kll-index {0 :backslash},
       :kll-value "U\"BACKSLASH\";",
       :line-comment "left fingers [1 1]"}
      {:hand :left,
       :section :fingers,
       :position [6 3],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [6 3]"}
      {:hand :left,
       :section :fingers,
       :position [3 4],
       :layer 0,
       :shortcut :3,
       :kll-index {0 :3, 1 :f3, 3 :f3, 4 :f13},
       :kll-value "U\"3\";",
       :line-comment "left fingers [3 4]"}
      {:hand :left,
       :section :fingers,
       :position [3 4],
       :layer 1,
       :shortcut :f3,
       :kll-index {0 :3, 1 :f3, 3 :f3, 4 :f13},
       :kll-value "U\"F3\";",
       :line-comment "left fingers [3 4]"}
      {:hand :left,
       :section :fingers,
       :position [3 4],
       :layer 3,
       :shortcut :f3,
       :kll-index {0 :3, 1 :f3, 3 :f3, 4 :f13},
       :kll-value "U\"F3\";",
       :line-comment "left fingers [3 4]"}
      {:hand :left,
       :section :fingers,
       :position [3 4],
       :layer 4,
       :shortcut :f13,
       :kll-index {0 :3, 1 :f3, 3 :f3, 4 :f13},
       :kll-value "U\"F13\";",
       :line-comment "left fingers [3 4]"}
      {:hand :left,
       :section :fingers,
       :position [4 2],
       :layer 0,
       :shortcut :u,
       :kll-index {0 :u},
       :kll-value "U\"U\";",
       :line-comment "left fingers [4 2]"}
      {:hand :left,
       :section :fingers,
       :position [3 0],
       :layer 0,
       :shortcut :k,
       :kll-index {0 :k, 2 :cursive/kill-sexp},
       :kll-value "U\"K\";",
       :line-comment "left fingers [3 0]"}
      {:hand :left,
       :section :fingers,
       :position [3 0],
       :layer 2,
       :shortcut :cursive/kill-sexp,
       :kll-index {0 :k, 2 :cursive/kill-sexp},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"K\";",
       :line-comment "left fingers [3 0]"}
      {:hand :left,
       :section :fingers,
       :position [5 3],
       :layer 0,
       :shortcut :y,
       :kll-index {0 :y},
       :kll-value "U\"Y\";",
       :line-comment "left fingers [5 3]"}
      {:hand :left,
       :section :fingers,
       :position [4 1],
       :layer 0,
       :shortcut :fun1,
       :kll-index {0 :fun1, 2 :cursive/send-top-form-to-repl},
       :kll-value "U\"FUN1\";",
       :line-comment "left fingers [4 1]"}
      {:hand :left,
       :section :fingers,
       :position [4 1],
       :layer 2,
       :shortcut :cursive/send-top-form-to-repl,
       :kll-index {0 :fun1, 2 :cursive/send-top-form-to-repl},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"T\";",
       :line-comment "left fingers [4 1]"}
      {:hand :left,
       :section :fingers,
       :position [5 2],
       :layer 0,
       :shortcut :i,
       :kll-index {0 :i},
       :kll-value "U\"I\";",
       :line-comment "left fingers [5 2]"}
      {:hand :left,
       :section :fingers,
       :position [1 4],
       :layer 0,
       :shortcut :1,
       :kll-index {0 :1, 1 :f1, 3 :f1, 4 :f12},
       :kll-value "U\"1\";",
       :line-comment "left fingers [1 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 4],
       :layer 1,
       :shortcut :f1,
       :kll-index {0 :1, 1 :f1, 3 :f1, 4 :f12},
       :kll-value "U\"F1\";",
       :line-comment "left fingers [1 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 4],
       :layer 3,
       :shortcut :f1,
       :kll-index {0 :1, 1 :f1, 3 :f1, 4 :f12},
       :kll-value "U\"F1\";",
       :line-comment "left fingers [1 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 4],
       :layer 4,
       :shortcut :f12,
       :kll-index {0 :1, 1 :f1, 3 :f1, 4 :f12},
       :kll-value "U\"F12\";",
       :line-comment "left fingers [1 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 3],
       :layer 0,
       :shortcut :tab,
       :kll-index {0 :tab},
       :kll-value "U\"TAB\";",
       :line-comment "left fingers [1 3]"}
      {:hand :left,
       :section :fingers,
       :position [6 4],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [6 4]"}
      {:hand :left,
       :section :fingers,
       :position [0 3],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [0 3]"}
      {:hand :left,
       :section :fingers,
       :position [5 1],
       :layer 0,
       :shortcut :x,
       :kll-index {0 :x},
       :kll-value "U\"X\";",
       :line-comment "left fingers [5 1]"}
      {:hand :left,
       :section :fingers,
       :position [6 1],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [6 1]"}
      {:hand :left,
       :section :fingers,
       :position [2 4],
       :layer 0,
       :shortcut :2,
       :kll-index {0 :2, 1 :f2, 3 :f2, 4 :f12},
       :kll-value "U\"2\";",
       :line-comment "left fingers [2 4]"}
      {:hand :left,
       :section :fingers,
       :position [2 4],
       :layer 1,
       :shortcut :f2,
       :kll-index {0 :2, 1 :f2, 3 :f2, 4 :f12},
       :kll-value "U\"F2\";",
       :line-comment "left fingers [2 4]"}
      {:hand :left,
       :section :fingers,
       :position [2 4],
       :layer 3,
       :shortcut :f2,
       :kll-index {0 :2, 1 :f2, 3 :f2, 4 :f12},
       :kll-value "U\"F2\";",
       :line-comment "left fingers [2 4]"}
      {:hand :left,
       :section :fingers,
       :position [2 4],
       :layer 4,
       :shortcut :f12,
       :kll-index {0 :2, 1 :f2, 3 :f2, 4 :f12},
       :kll-value "U\"F12\";",
       :line-comment "left fingers [2 4]"}
      {:hand :left,
       :section :fingers,
       :position [0 2],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [0 2]"}
      {:hand :left,
       :section :fingers,
       :position [2 0],
       :layer 0,
       :shortcut :q,
       :kll-index {0 :q},
       :kll-value "U\"Q\";",
       :line-comment "left fingers [2 0]"}
      {:hand :left,
       :section :fingers,
       :position [0 4],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [0 4]"}
      {:hand :left,
       :section :fingers,
       :position [3 1],
       :layer 0,
       :shortcut :fun2,
       :kll-index {0 :fun2, 1 :cursive/send-top-form-to-repl},
       :kll-value "U\"FUN2\";",
       :line-comment "left fingers [3 1]"}
      {:hand :left,
       :section :fingers,
       :position [3 1],
       :layer 1,
       :shortcut :cursive/send-top-form-to-repl,
       :kll-index {0 :fun2, 1 :cursive/send-top-form-to-repl},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"T\";",
       :line-comment "left fingers [3 1]"}
      {:hand :left,
       :section :fingers,
       :position [2 1],
       :layer 0,
       :shortcut :j,
       :kll-index {0 :j, 1 :cursive/send-form-before-to-repl},
       :kll-value "U\"J\";",
       :line-comment "left fingers [2 1]"}
      {:hand :left,
       :section :fingers,
       :position [2 1],
       :layer 1,
       :shortcut :cursive/send-form-before-to-repl,
       :kll-index {0 :j, 1 :cursive/send-form-before-to-repl},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"B\";",
       :line-comment "left fingers [2 1]"}
      {:hand :left,
       :section :fingers,
       :position [4 4],
       :layer 0,
       :shortcut :4,
       :kll-index {0 :4, 1 :f4, 3 :f4, 4 :f14},
       :kll-value "U\"4\";",
       :line-comment "left fingers [4 4]"}
      {:hand :left,
       :section :fingers,
       :position [4 4],
       :layer 1,
       :shortcut :f4,
       :kll-index {0 :4, 1 :f4, 3 :f4, 4 :f14},
       :kll-value "U\"F4\";",
       :line-comment "left fingers [4 4]"}
      {:hand :left,
       :section :fingers,
       :position [4 4],
       :layer 3,
       :shortcut :f4,
       :kll-index {0 :4, 1 :f4, 3 :f4, 4 :f14},
       :kll-value "U\"F4\";",
       :line-comment "left fingers [4 4]"}
      {:hand :left,
       :section :fingers,
       :position [4 4],
       :layer 4,
       :shortcut :f14,
       :kll-index {0 :4, 1 :f4, 3 :f4, 4 :f14},
       :kll-value "U\"F14\";",
       :line-comment "left fingers [4 4]"}
      {:hand :left,
       :section :fingers,
       :position [1 2],
       :layer 0,
       :shortcut :delete,
       :kll-index {0 :delete},
       :kll-value "U\"DELETE\";",
       :line-comment "left fingers [1 2]"}
      {:hand :left,
       :section :fingers,
       :position [3 2],
       :layer 0,
       :shortcut :e,
       :kll-index {0 :e, 1 :cursive/extend-selection},
       :kll-value "U\"E\";",
       :line-comment "left fingers [3 2]"}
      {:hand :left,
       :section :fingers,
       :position [3 2],
       :layer 1,
       :shortcut :cursive/extend-selection,
       :kll-index {0 :e, 1 :cursive/extend-selection},
       :kll-value "U\"W\" + U\"CTRL\";",
       :line-comment "left fingers [3 2]"}
      {:hand :left,
       :section :fingers,
       :position [0 1],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "left fingers [0 1]"}
      {:hand :left,
       :section :fingers,
       :position [4 0],
       :layer 0,
       :shortcut :s,
       :kll-index {0 :s, 2 :cursive/split-sexp},
       :kll-value "U\"S\";",
       :line-comment "left fingers [4 0]"}
      {:hand :left,
       :section :fingers,
       :position [4 0],
       :layer 2,
       :shortcut :cursive/split-sexp,
       :kll-index {0 :s, 2 :cursive/split-sexp},
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"S\";",
       :line-comment "left fingers [4 0]"}
      {:hand :right,
       :section :thumb,
       :position [0 0],
       :layer 0,
       :shortcut :space,
       :kll-index {0 :space},
       :kll-value "U\"SPACE\";",
       :line-comment "right thumb [0 0]"}
      {:hand :right,
       :section :thumb,
       :position [1 0],
       :layer 0,
       :shortcut :rshift,
       :kll-index {0 :rshift},
       :kll-value "U\"RSHIFT\";",
       :line-comment "right thumb [1 0]"}
      {:hand :right,
       :section :thumb,
       :position [1 2],
       :layer 0,
       :shortcut :ralt,
       :kll-index {0 :ralt},
       :kll-value "U\"RALT\";",
       :line-comment "right thumb [1 2]"}
      {:hand :right,
       :section :thumb,
       :position [2 0],
       :layer 0,
       :shortcut :escape,
       :kll-index {0 :escape},
       :kll-value "U\"ESCAPE\";",
       :line-comment "right thumb [2 0]"}
      {:hand :right,
       :section :thumb,
       :position [2 1],
       :layer 0,
       :shortcut :rgui,
       :kll-index {0 :rgui, 1 :app},
       :kll-value "U\"RGUI\";",
       :line-comment "right thumb [2 1]"}
      {:hand :right,
       :section :thumb,
       :position [2 1],
       :layer 1,
       :shortcut :app,
       :kll-index {0 :rgui, 1 :app},
       :kll-value "U\"APP\";",
       :line-comment "right thumb [2 1]"}
      {:hand :right,
       :section :thumb,
       :position [2 2],
       :layer 0,
       :shortcut :ralt,
       :kll-index {0 :ralt},
       :kll-value "U\"RALT\";",
       :line-comment "right thumb [2 2]"}
      {:hand :right,
       :section :fingers,
       :position [4 3],
       :layer 0,
       :shortcut :g,
       :kll-index {0 :g, 2 :home},
       :kll-value "U\"G\";",
       :line-comment "right fingers [4 3]"}
      {:hand :right,
       :section :fingers,
       :position [4 3],
       :layer 2,
       :shortcut :home,
       :kll-index {0 :g, 2 :home},
       :kll-value "U\"HOME\";",
       :line-comment "right fingers [4 3]"}
      {:hand :right,
       :section :fingers,
       :position [2 2],
       :layer 0,
       :shortcut :n,
       :kll-index {0 :n, 2 :right, 3 :rbracket, 4 :question-mark},
       :kll-value "U\"N\";",
       :line-comment "right fingers [2 2]"}
      {:hand :right,
       :section :fingers,
       :position [2 2],
       :layer 2,
       :shortcut :right,
       :kll-index {0 :n, 2 :right, 3 :rbracket, 4 :question-mark},
       :kll-value "U\"RIGHT\";",
       :line-comment "right fingers [2 2]"}
      {:hand :right,
       :section :fingers,
       :position [2 2],
       :layer 3,
       :shortcut :rbracket,
       :kll-index {0 :n, 2 :right, 3 :rbracket, 4 :question-mark},
       :kll-value "U\"RBRACKET\";",
       :line-comment "right fingers [2 2]"}
      {:hand :right,
       :section :fingers,
       :position [2 2],
       :layer 4,
       :shortcut :question-mark,
       :kll-index {0 :n, 2 :right, 3 :rbracket, 4 :question-mark},
       :kll-value "'?';",
       :line-comment "right fingers [2 2]"}
      {:hand :right,
       :section :fingers,
       :position [0 0],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [0 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 0,
       :shortcut :z,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"Z\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 1,
       :shortcut :lat1,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"LAT1\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 2,
       :shortcut :lat2,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"LAT2\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 3,
       :shortcut :lat3,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"LAT3\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 4,
       :shortcut :lat4,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"LAT4\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [1 0],
       :layer 5,
       :shortcut :lat5,
       :kll-index {0 :z, 1 :lat1, 2 :lat2, 3 :lat3, 4 :lat4, 5 :lat5},
       :kll-value "U\"LAT5\";",
       :line-comment "right fingers [1 0]"}
      {:hand :right,
       :section :fingers,
       :position [2 3],
       :layer 0,
       :shortcut :r,
       :kll-index {0 :r, 1 :cursive/raise-form, 2 :end, 3 :right-curly-brace},
       :kll-value "U\"R\";",
       :line-comment "right fingers [2 3]"}
      {:hand :right,
       :section :fingers,
       :position [2 3],
       :layer 1,
       :shortcut :cursive/raise-form,
       :kll-index {0 :r, 1 :cursive/raise-form, 2 :end, 3 :right-curly-brace},
       :kll-value "U\"R\" + U\"ALT\";",
       :line-comment "right fingers [2 3]"}
      {:hand :right,
       :section :fingers,
       :position [2 3],
       :layer 2,
       :shortcut :end,
       :kll-index {0 :r, 1 :cursive/raise-form, 2 :end, 3 :right-curly-brace},
       :kll-value "U\"END\";",
       :line-comment "right fingers [2 3]"}
      {:hand :right,
       :section :fingers,
       :position [2 3],
       :layer 3,
       :shortcut :right-curly-brace,
       :kll-index {0 :r, 1 :cursive/raise-form, 2 :end, 3 :right-curly-brace},
       :kll-value "'}';",
       :line-comment "right fingers [2 3]"}
      {:hand :right,
       :section :fingers,
       :position [3 3],
       :layer 0,
       :shortcut :c,
       :kll-index {0 :c, 1 :cursive/move-form-up, 2 :up, 3 :left-curly-brace},
       :kll-value "U\"C\";",
       :line-comment "right fingers [3 3]"}
      {:hand :right,
       :section :fingers,
       :position [3 3],
       :layer 1,
       :shortcut :cursive/move-form-up,
       :kll-index {0 :c, 1 :cursive/move-form-up, 2 :up, 3 :left-curly-brace},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"UP\";",
       :line-comment "right fingers [3 3]"}
      {:hand :right,
       :section :fingers,
       :position [3 3],
       :layer 2,
       :shortcut :up,
       :kll-index {0 :c, 1 :cursive/move-form-up, 2 :up, 3 :left-curly-brace},
       :kll-value "U\"UP\";",
       :line-comment "right fingers [3 3]"}
      {:hand :right,
       :section :fingers,
       :position [3 3],
       :layer 3,
       :shortcut :left-curly-brace,
       :kll-index {0 :c, 1 :cursive/move-form-up, 2 :up, 3 :left-curly-brace},
       :kll-value "'{';",
       :line-comment "right fingers [3 3]"}
      {:hand :right,
       :section :fingers,
       :position [5 4],
       :layer 0,
       :shortcut :6,
       :kll-index {0 :6, 1 :f6},
       :kll-value "U\"6\";",
       :line-comment "right fingers [5 4]"}
      {:hand :right,
       :section :fingers,
       :position [5 4],
       :layer 1,
       :shortcut :f6,
       :kll-index {0 :6, 1 :f6},
       :kll-value "U\"F6\";",
       :line-comment "right fingers [5 4]"}
      {:hand :right,
       :section :fingers,
       :position [1 1],
       :layer 0,
       :shortcut :enter,
       :kll-index {0 :enter, 3 :cursive/wrap-with-round-braces},
       :kll-value "U\"ENTER\";",
       :line-comment "right fingers [1 1]"}
      {:hand :right,
       :section :fingers,
       :position [1 1],
       :layer 3,
       :shortcut :cursive/wrap-with-round-braces,
       :kll-index {0 :enter, 3 :cursive/wrap-with-round-braces},
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"9\";",
       :line-comment "right fingers [1 1]"}
      {:hand :right,
       :section :fingers,
       :position [6 3],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [6 3]"}
      {:hand :right,
       :section :fingers,
       :position [3 4],
       :layer 0,
       :shortcut :8,
       :kll-index {0 :8, 1 :f8, 3 :clj/thread-first-backwards},
       :kll-value "U\"8\";",
       :line-comment "right fingers [3 4]"}
      {:hand :right,
       :section :fingers,
       :position [3 4],
       :layer 1,
       :shortcut :f8,
       :kll-index {0 :8, 1 :f8, 3 :clj/thread-first-backwards},
       :kll-value "U\"F8\";",
       :line-comment "right fingers [3 4]"}
      {:hand :right,
       :section :fingers,
       :position [3 4],
       :layer 3,
       :shortcut :clj/thread-first-backwards,
       :kll-index {0 :8, 1 :f8, 3 :clj/thread-first-backwards},
       :kll-value "'<-';",
       :line-comment "right fingers [3 4]"}
      {:hand :right,
       :section :fingers,
       :position [4 2],
       :layer 0,
       :shortcut :h,
       :kll-index {0 :h,
                   2 :left,
                   3 :cursive/wrap-with-double-quotes,
                   4 :equals,
                   5 :double-quote},
       :kll-value "U\"H\";",
       :line-comment "right fingers [4 2]"}
      {:hand :right,
       :section :fingers,
       :position [4 2],
       :layer 2,
       :shortcut :left,
       :kll-index {0 :h,
                   2 :left,
                   3 :cursive/wrap-with-double-quotes,
                   4 :equals,
                   5 :double-quote},
       :kll-value "U\"LEFT\";",
       :line-comment "right fingers [4 2]"}
      {:hand :right,
       :section :fingers,
       :position [4 2],
       :layer 3,
       :shortcut :cursive/wrap-with-double-quotes,
       :kll-index {0 :h,
                   2 :left,
                   3 :cursive/wrap-with-double-quotes,
                   4 :equals,
                   5 :double-quote},
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"QUOTE\";",
       :line-comment "right fingers [4 2]"}
      {:hand :right,
       :section :fingers,
       :position [4 2],
       :layer 4,
       :shortcut :equals,
       :kll-index {0 :h,
                   2 :left,
                   3 :cursive/wrap-with-double-quotes,
                   4 :equals,
                   5 :double-quote},
       :kll-value "U\"EQUALS\";",
       :line-comment "right fingers [4 2]"}
      {:hand :right,
       :section :fingers,
       :position [4 2],
       :layer 5,
       :shortcut :double-quote,
       :kll-index {0 :h,
                   2 :left,
                   3 :cursive/wrap-with-double-quotes,
                   4 :equals,
                   5 :double-quote},
       :kll-value "'\"';",
       :line-comment "right fingers [4 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 0],
       :layer 0,
       :shortcut :w,
       :kll-index {0 :w,
                   1 :cursive/join-sexp,
                   2 :cursive/sexp-down-right,
                   3 :left-angle-brace,
                   5 :comma},
       :kll-value "U\"W\";",
       :line-comment "right fingers [3 0]"}
      {:hand :right,
       :section :fingers,
       :position [3 0],
       :layer 1,
       :shortcut :cursive/join-sexp,
       :kll-index {0 :w,
                   1 :cursive/join-sexp,
                   2 :cursive/sexp-down-right,
                   3 :left-angle-brace,
                   5 :comma},
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"J\";",
       :line-comment "right fingers [3 0]"}
      {:hand :right,
       :section :fingers,
       :position [3 0],
       :layer 2,
       :shortcut :cursive/sexp-down-right,
       :kll-index {0 :w,
                   1 :cursive/join-sexp,
                   2 :cursive/sexp-down-right,
                   3 :left-angle-brace,
                   5 :comma},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"D\";",
       :line-comment "right fingers [3 0]"}
      {:hand :right,
       :section :fingers,
       :position [3 0],
       :layer 3,
       :shortcut :left-angle-brace,
       :kll-index {0 :w,
                   1 :cursive/join-sexp,
                   2 :cursive/sexp-down-right,
                   3 :left-angle-brace,
                   5 :comma},
       :kll-value "'<';",
       :line-comment "right fingers [3 0]"}
      {:hand :right,
       :section :fingers,
       :position [3 0],
       :layer 5,
       :shortcut :comma,
       :kll-index {0 :w,
                   1 :cursive/join-sexp,
                   2 :cursive/sexp-down-right,
                   3 :left-angle-brace,
                   5 :comma},
       :kll-value "U\"COMMA\";",
       :line-comment "right fingers [3 0]"}
      {:hand :right,
       :section :fingers,
       :position [5 3],
       :layer 0,
       :shortcut :f,
       :kll-index {0 :f, 2 :pageup},
       :kll-value "U\"F\";",
       :line-comment "right fingers [5 3]"}
      {:hand :right,
       :section :fingers,
       :position [5 3],
       :layer 2,
       :shortcut :pageup,
       :kll-index {0 :f, 2 :pageup},
       :kll-value "U\"PAGEUP\";",
       :line-comment "right fingers [5 3]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 0,
       :shortcut :fun3,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "U\"FUN3\";",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 1,
       :shortcut :cursive/slurp-forward,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "U\"SHIFT\" + U\"0\" + U\"CTRL\";",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 2,
       :shortcut :cursive/sexp-down-left,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"P\";",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 3,
       :shortcut :fun3,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "U\"FUN3\";",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 4,
       :shortcut :minus,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "U\"MINUS\";",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 1],
       :layer 5,
       :shortcut :colon,
       :kll-index {0 :fun3,
                   1 :cursive/slurp-forward,
                   2 :cursive/sexp-down-left,
                   3 :fun3,
                   4 :minus,
                   5 :colon},
       :kll-value "':';",
       :line-comment "right fingers [4 1]"}
      {:hand :right,
       :section :fingers,
       :position [5 2],
       :layer 0,
       :shortcut :d,
       :kll-index {0 :d, 2 :previous-word, 5 :backtick},
       :kll-value "U\"D\";",
       :line-comment "right fingers [5 2]"}
      {:hand :right,
       :section :fingers,
       :position [5 2],
       :layer 2,
       :shortcut :previous-word,
       :kll-index {0 :d, 2 :previous-word, 5 :backtick},
       :kll-value "U\"CTRL\" + U\"LEFT\";",
       :line-comment "right fingers [5 2]"}
      {:hand :right,
       :section :fingers,
       :position [5 2],
       :layer 5,
       :shortcut :backtick,
       :kll-index {0 :d, 2 :previous-word, 5 :backtick},
       :kll-value "U\"BACKTICK\";",
       :line-comment "right fingers [5 2]"}
      {:hand :right,
       :section :fingers,
       :position [1 4],
       :layer 0,
       :shortcut :0,
       :kll-index {0 :0, 1 :f10, 3 :clj/thread-last},
       :kll-value "U\"0\";",
       :line-comment "right fingers [1 4]"}
      {:hand :right,
       :section :fingers,
       :position [1 4],
       :layer 1,
       :shortcut :f10,
       :kll-index {0 :0, 1 :f10, 3 :clj/thread-last},
       :kll-value "U\"F10\";",
       :line-comment "right fingers [1 4]"}
      {:hand :right,
       :section :fingers,
       :position [1 4],
       :layer 3,
       :shortcut :clj/thread-last,
       :kll-index {0 :0, 1 :f10, 3 :clj/thread-last},
       :kll-value "'->>';",
       :line-comment "right fingers [1 4]"}
      {:hand :right,
       :section :fingers,
       :position [1 3],
       :layer 0,
       :shortcut :backspace,
       :kll-index {0 :backspace, 2 :pagedown, 3 :cursive/wrap-with-curly-braces},
       :kll-value "U\"BACKSPACE\";",
       :line-comment "right fingers [1 3]"}
      {:hand :right,
       :section :fingers,
       :position [1 3],
       :layer 2,
       :shortcut :pagedown,
       :kll-index {0 :backspace, 2 :pagedown, 3 :cursive/wrap-with-curly-braces},
       :kll-value "U\"PAGEDOWN\";",
       :line-comment "right fingers [1 3]"}
      {:hand :right,
       :section :fingers,
       :position [1 3],
       :layer 3,
       :shortcut :cursive/wrap-with-curly-braces,
       :kll-index {0 :backspace, 2 :pagedown, 3 :cursive/wrap-with-curly-braces},
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"LBRACKET\";",
       :line-comment "right fingers [1 3]"}
      {:hand :right,
       :section :fingers,
       :position [6 4],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [6 4]"}
      {:hand :right,
       :section :fingers,
       :position [0 3],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [0 3]"}
      {:hand :right,
       :section :fingers,
       :position [5 1],
       :layer 0,
       :shortcut :b,
       :kll-index {0 :b, 5 :tilde},
       :kll-value "U\"B\";",
       :line-comment "right fingers [5 1]"}
      {:hand :right,
       :section :fingers,
       :position [5 1],
       :layer 5,
       :shortcut :tilde,
       :kll-index {0 :b, 5 :tilde},
       :kll-value "'~';",
       :line-comment "right fingers [5 1]"}
      {:hand :right,
       :section :fingers,
       :position [6 1],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [6 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 4],
       :layer 0,
       :shortcut :9,
       :kll-index {0 :9, 1 :f9, 3 :clj/thread-first},
       :kll-value "U\"9\";",
       :line-comment "right fingers [2 4]"}
      {:hand :right,
       :section :fingers,
       :position [2 4],
       :layer 1,
       :shortcut :f9,
       :kll-index {0 :9, 1 :f9, 3 :clj/thread-first},
       :kll-value "U\"F9\";",
       :line-comment "right fingers [2 4]"}
      {:hand :right,
       :section :fingers,
       :position [2 4],
       :layer 3,
       :shortcut :clj/thread-first,
       :kll-index {0 :9, 1 :f9, 3 :clj/thread-first},
       :kll-value "'->';",
       :line-comment "right fingers [2 4]"}
      {:hand :right,
       :section :fingers,
       :position [0 2],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [0 2]"}
      {:hand :right,
       :section :fingers,
       :position [2 0],
       :layer 0,
       :shortcut :v,
       :kll-index {0 :v,
                   2 :cursive/sexp-right,
                   3 :right-angle-brace,
                   4 :backslash},
       :kll-value "U\"V\";",
       :line-comment "right fingers [2 0]"}
      {:hand :right,
       :section :fingers,
       :position [2 0],
       :layer 2,
       :shortcut :cursive/sexp-right,
       :kll-index {0 :v,
                   2 :cursive/sexp-right,
                   3 :right-angle-brace,
                   4 :backslash},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"F\";",
       :line-comment "right fingers [2 0]"}
      {:hand :right,
       :section :fingers,
       :position [2 0],
       :layer 3,
       :shortcut :right-angle-brace,
       :kll-index {0 :v,
                   2 :cursive/sexp-right,
                   3 :right-angle-brace,
                   4 :backslash},
       :kll-value "'>';",
       :line-comment "right fingers [2 0]"}
      {:hand :right,
       :section :fingers,
       :position [2 0],
       :layer 4,
       :shortcut :backslash,
       :kll-index {0 :v,
                   2 :cursive/sexp-right,
                   3 :right-angle-brace,
                   4 :backslash},
       :kll-value "U\"BACKSLASH\";",
       :line-comment "right fingers [2 0]"}
      {:hand :right,
       :section :fingers,
       :position [0 4],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [0 4]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 0,
       :shortcut :fun4,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "U\"FUN4\";",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 1,
       :shortcut :cursive/splice-sexp,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "U\"ALT\" + U\"S\";",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 2,
       :shortcut :cursive/sexp-up-left,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"U\";",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 3,
       :shortcut :left-round-brace,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "'(';",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 4,
       :shortcut :fun4,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "U\"FUN4\";",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [3 1],
       :layer 5,
       :shortcut :period,
       :kll-index {0 :fun4,
                   1 :cursive/splice-sexp,
                   2 :cursive/sexp-up-left,
                   3 :left-round-brace,
                   4 :fun4,
                   5 :period},
       :kll-value "U\"PERIOD\";",
       :line-comment "right fingers [3 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 0,
       :shortcut :fun5,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "U\"FUN5\";",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 1,
       :shortcut :cursive/barf-forward,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"RBRACE\";",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 2,
       :shortcut :cursive/sexp-up-right,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "U\"ALT\" + U\"N\" + U\"CTRL\";",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 3,
       :shortcut :right-round-brace,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "')';",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 4,
       :shortcut :slash,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "U\"SLASH\";",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [2 1],
       :layer 5,
       :shortcut :fun5,
       :kll-index {0 :fun5,
                   1 :cursive/barf-forward,
                   2 :cursive/sexp-up-right,
                   3 :right-round-brace,
                   4 :slash,
                   5 :fun5},
       :kll-value "U\"FUN5\";",
       :line-comment "right fingers [2 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 4],
       :layer 0,
       :shortcut :7,
       :kll-index {0 :7, 1 :f7, 3 :clj/thread-last-backwards},
       :kll-value "U\"7\";",
       :line-comment "right fingers [4 4]"}
      {:hand :right,
       :section :fingers,
       :position [4 4],
       :layer 1,
       :shortcut :f7,
       :kll-index {0 :7, 1 :f7, 3 :clj/thread-last-backwards},
       :kll-value "U\"F7\";",
       :line-comment "right fingers [4 4]"}
      {:hand :right,
       :section :fingers,
       :position [4 4],
       :layer 3,
       :shortcut :clj/thread-last-backwards,
       :kll-index {0 :7, 1 :f7, 3 :clj/thread-last-backwards},
       :kll-value "'<<-';",
       :line-comment "right fingers [4 4]"}
      {:hand :right,
       :section :fingers,
       :position [1 2],
       :layer 0,
       :shortcut :escape,
       :kll-index {0 :escape, 2 :next-word, 3 :cursive/wrap-with-square-braces},
       :kll-value "U\"ESCAPE\";",
       :line-comment "right fingers [1 2]"}
      {:hand :right,
       :section :fingers,
       :position [1 2],
       :layer 2,
       :shortcut :next-word,
       :kll-index {0 :escape, 2 :next-word, 3 :cursive/wrap-with-square-braces},
       :kll-value "U\"CTRL\" + U\"RIGHT\";",
       :line-comment "right fingers [1 2]"}
      {:hand :right,
       :section :fingers,
       :position [1 2],
       :layer 3,
       :shortcut :cursive/wrap-with-square-braces,
       :kll-index {0 :escape, 2 :next-word, 3 :cursive/wrap-with-square-braces},
       :kll-value "U\"ALT\" + U\"LBRACKET\";",
       :line-comment "right fingers [1 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 2],
       :layer 0,
       :shortcut :t,
       :kll-index {0 :t,
                   1 :cursive/move-form-down,
                   2 :down,
                   3 :lbracket,
                   5 :quote},
       :kll-value "U\"T\";",
       :line-comment "right fingers [3 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 2],
       :layer 1,
       :shortcut :cursive/move-form-down,
       :kll-index {0 :t,
                   1 :cursive/move-form-down,
                   2 :down,
                   3 :lbracket,
                   5 :quote},
       :kll-value "U\"SHIFT\" + U\"DOWN\" + U\"CTRL\";",
       :line-comment "right fingers [3 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 2],
       :layer 2,
       :shortcut :down,
       :kll-index {0 :t,
                   1 :cursive/move-form-down,
                   2 :down,
                   3 :lbracket,
                   5 :quote},
       :kll-value "U\"DOWN\";",
       :line-comment "right fingers [3 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 2],
       :layer 3,
       :shortcut :lbracket,
       :kll-index {0 :t,
                   1 :cursive/move-form-down,
                   2 :down,
                   3 :lbracket,
                   5 :quote},
       :kll-value "U\"LBRACKET\";",
       :line-comment "right fingers [3 2]"}
      {:hand :right,
       :section :fingers,
       :position [3 2],
       :layer 5,
       :shortcut :quote,
       :kll-index {0 :t,
                   1 :cursive/move-form-down,
                   2 :down,
                   3 :lbracket,
                   5 :quote},
       :kll-value "U\"QUOTE\";",
       :line-comment "right fingers [3 2]"}
      {:hand :right,
       :section :fingers,
       :position [0 1],
       :layer 0,
       :shortcut nil,
       :kll-index {0 nil},
       :kll-value "None;",
       :line-comment "right fingers [0 1]"}
      {:hand :right,
       :section :fingers,
       :position [4 0],
       :layer 0,
       :shortcut :m,
       :kll-index {0 :m,
                   2 :cursive/sexp-left,
                   3 :underscore,
                   4 :plus,
                   5 :semicolon},
       :kll-value "U\"M\";",
       :line-comment "right fingers [4 0]"}
      {:hand :right,
       :section :fingers,
       :position [4 0],
       :layer 2,
       :shortcut :cursive/sexp-left,
       :kll-index {0 :m,
                   2 :cursive/sexp-left,
                   3 :underscore,
                   4 :plus,
                   5 :semicolon},
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"B\";",
       :line-comment "right fingers [4 0]"}
      {:hand :right,
       :section :fingers,
       :position [4 0],
       :layer 3,
       :shortcut :underscore,
       :kll-index {0 :m,
                   2 :cursive/sexp-left,
                   3 :underscore,
                   4 :plus,
                   5 :semicolon},
       :kll-value "'_';",
       :line-comment "right fingers [4 0]"}
      {:hand :right,
       :section :fingers,
       :position [4 0],
       :layer 4,
       :shortcut :plus,
       :kll-index {0 :m,
                   2 :cursive/sexp-left,
                   3 :underscore,
                   4 :plus,
                   5 :semicolon},
       :kll-value "'+';",
       :line-comment "right fingers [4 0]"}
      {:hand :right,
       :section :fingers,
       :position [4 0],
       :layer 5,
       :shortcut :semicolon,
       :kll-index {0 :m,
                   2 :cursive/sexp-left,
                   3 :underscore,
                   4 :plus,
                   5 :semicolon},
       :kll-value "U\"SEMICOLON\";",
       :line-comment "right fingers [4 0]"}]}
