(let [kll-header "resources/kll-header.txt"
      layout "resources/ergodox-keymap.edn"]
  (make-kll-file-bodies kll-header layout))
=>
{:exploded [{:hand :left,
             :finger :p,
             :position [0 0],
             :layer 0,
             :shortcut :lctrl}
            {:hand :left,
             :finger :p,
             :position [1 0],
             :layer 0,
             :shortcut :lalt}
            {:hand :left,
             :finger :p,
             :position [1 2],
             :layer 0,
             :shortcut :lshift}
            {:hand :left,
             :finger :p,
             :position [2 0],
             :layer 0,
             :shortcut :escape}
            {:hand :left,
             :finger :p,
             :position [2 1],
             :layer 0,
             :shortcut :lgui}
            {:hand :left, :finger :p, :position [2 1], :layer 1, :shortcut :app}
            {:hand :left,
             :finger :p,
             :position [2 2],
             :layer 0,
             :shortcut :space}
            {:hand :left, :finger :i, :position [2 2], :layer 0, :shortcut nil}
            {:hand :left,
             :finger :i,
             :position [0 0],
             :layer 0,
             :shortcut :fun1}
            {:hand :left,
             :finger :i,
             :position [0 0],
             :layer 2,
             :shortcut :cursive/send-top-form-to-repl}
            {:hand :left, :finger :i, :position [1 0], :layer 0, :shortcut :x}
            {:hand :left, :finger :i, :position [2 3], :layer 0, :shortcut nil}
            {:hand :left,
             :finger :i,
             :position [2 3],
             :layer 1,
             :shortcut :firmware/flashmode}
            {:hand :left, :finger :i, :position [1 1], :layer 0, :shortcut :i}
            {:hand :left, :finger :i, :position [1 3], :layer 0, :shortcut :5}
            {:hand :left, :finger :i, :position [1 3], :layer 1, :shortcut :f5}
            {:hand :left, :finger :i, :position [1 3], :layer 3, :shortcut :f5}
            {:hand :left, :finger :i, :position [1 3], :layer 4, :shortcut :f15}
            {:hand :left, :finger :i, :position [0 3], :layer 0, :shortcut :4}
            {:hand :left, :finger :i, :position [0 3], :layer 1, :shortcut :f4}
            {:hand :left, :finger :i, :position [0 3], :layer 3, :shortcut :f4}
            {:hand :left, :finger :i, :position [0 3], :layer 4, :shortcut :f14}
            {:hand :left, :finger :i, :position [0 2], :layer 0, :shortcut :p}
            {:hand :left, :finger :i, :position [2 0], :layer 0, :shortcut nil}
            {:hand :left, :finger :i, :position [0 -1], :layer 0, :shortcut :s}
            {:hand :left,
             :finger :i,
             :position [0 -1],
             :layer 2,
             :shortcut :cursive/split-sexp}
            {:hand :left, :finger :i, :position [1 2], :layer 0, :shortcut :y}
            {:hand :left, :finger :i, :position [0 1], :layer 0, :shortcut :u}
            {:hand :left, :finger :m, :position [0 -1], :layer 0, :shortcut :k}
            {:hand :left,
             :finger :m,
             :position [0 -1],
             :layer 2,
             :shortcut :cursive/kill-sexp}
            {:hand :left,
             :finger :m,
             :position [0 0],
             :layer 0,
             :shortcut :fun2}
            {:hand :left,
             :finger :m,
             :position [0 0],
             :layer 1,
             :shortcut :cursive/send-top-form-to-repl}
            {:hand :left, :finger :m, :position [0 1], :layer 0, :shortcut :e}
            {:hand :left,
             :finger :m,
             :position [0 1],
             :layer 1,
             :shortcut :cursive/extend-selection}
            {:hand :left, :finger :m, :position [0 2], :layer 0, :shortcut :a}
            {:hand :left,
             :finger :m,
             :position [0 2],
             :layer 1,
             :shortcut :cursive/switch-repl-to-ns}
            {:hand :left, :finger :m, :position [0 3], :layer 0, :shortcut :3}
            {:hand :left, :finger :m, :position [0 3], :layer 1, :shortcut :f3}
            {:hand :left, :finger :m, :position [0 3], :layer 3, :shortcut :f3}
            {:hand :left, :finger :m, :position [0 3], :layer 4, :shortcut :f13}
            {:hand :left, :finger :a, :position [0 0], :layer 0, :shortcut :j}
            {:hand :left,
             :finger :a,
             :position [0 0],
             :layer 1,
             :shortcut :cursive/send-form-before-to-repl}
            {:hand :left, :finger :a, :position [-2 3], :layer 0, :shortcut nil}
            {:hand :left,
             :finger :a,
             :position [-1 0],
             :layer 0,
             :shortcut :backslash}
            {:hand :left, :finger :a, :position [-1 3], :layer 0, :shortcut :1}
            {:hand :left, :finger :a, :position [-1 3], :layer 1, :shortcut :f1}
            {:hand :left, :finger :a, :position [-1 3], :layer 3, :shortcut :f1}
            {:hand :left,
             :finger :a,
             :position [-1 3],
             :layer 4,
             :shortcut :f12}
            {:hand :left,
             :finger :a,
             :position [-1 2],
             :layer 0,
             :shortcut :tab}
            {:hand :left,
             :finger :a,
             :position [-1 -1],
             :layer 0,
             :shortcut nil}
            {:hand :left, :finger :a, :position [-2 1], :layer 0, :shortcut nil}
            {:hand :left,
             :finger :a,
             :position [-2 -1],
             :layer 0,
             :shortcut nil}
            {:hand :left, :finger :a, :position [0 3], :layer 0, :shortcut :2}
            {:hand :left, :finger :a, :position [0 3], :layer 1, :shortcut :f2}
            {:hand :left, :finger :a, :position [0 3], :layer 3, :shortcut :f2}
            {:hand :left, :finger :a, :position [0 3], :layer 4, :shortcut :f12}
            {:hand :left, :finger :a, :position [-2 2], :layer 0, :shortcut nil}
            {:hand :left, :finger :a, :position [0 2], :layer 0, :shortcut :l}
            {:hand :left,
             :finger :a,
             :position [0 2],
             :layer 1,
             :shortcut :cursive/load-file-in-repl}
            {:hand :left,
             :finger :a,
             :position [-1 1],
             :layer 0,
             :shortcut :delete}
            {:hand :left, :finger :a, :position [0 -1], :layer 0, :shortcut :q}
            {:hand :left, :finger :a, :position [-2 0], :layer 0, :shortcut nil}
            {:hand :left, :finger :a, :position [0 1], :layer 0, :shortcut :o}
            {:hand :left,
             :finger :a,
             :position [0 1],
             :layer 1,
             :shortcut :cursive/shrink-selection}
            {:hand :right,
             :finger :p,
             :position [0 0],
             :layer 0,
             :shortcut :space}
            {:hand :right,
             :finger :p,
             :position [1 0],
             :layer 0,
             :shortcut :rshift}
            {:hand :right,
             :finger :p,
             :position [1 2],
             :layer 0,
             :shortcut :ralt}
            {:hand :right,
             :finger :p,
             :position [2 0],
             :layer 0,
             :shortcut :escape}
            {:hand :right,
             :finger :p,
             :position [2 1],
             :layer 0,
             :shortcut :rgui}
            {:hand :right,
             :finger :p,
             :position [2 1],
             :layer 1,
             :shortcut :app}
            {:hand :right,
             :finger :p,
             :position [2 2],
             :layer 0,
             :shortcut :ralt}
            {:hand :right, :finger :i, :position [2 2], :layer 0, :shortcut nil}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 0,
             :shortcut :fun3}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 1,
             :shortcut :cursive/slurp-forward}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 2,
             :shortcut :cursive/sexp-down-left}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 3,
             :shortcut :fun3}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 4,
             :shortcut :minus}
            {:hand :right,
             :finger :i,
             :position [0 0],
             :layer 5,
             :shortcut :colon}
            {:hand :right, :finger :i, :position [1 0], :layer 0, :shortcut :b}
            {:hand :right,
             :finger :i,
             :position [1 0],
             :layer 5,
             :shortcut :tilde}
            {:hand :right, :finger :i, :position [2 3], :layer 0, :shortcut nil}
            {:hand :right,
             :finger :i,
             :position [2 3],
             :layer 3,
             :shortcut :firmware/flashmode}
            {:hand :right, :finger :i, :position [1 1], :layer 0, :shortcut :d}
            {:hand :right,
             :finger :i,
             :position [1 1],
             :layer 2,
             :shortcut :previous-word}
            {:hand :right,
             :finger :i,
             :position [1 1],
             :layer 5,
             :shortcut :backtick}
            {:hand :right, :finger :i, :position [1 3], :layer 0, :shortcut :6}
            {:hand :right, :finger :i, :position [1 3], :layer 1, :shortcut :f6}
            {:hand :right, :finger :i, :position [0 3], :layer 0, :shortcut :7}
            {:hand :right, :finger :i, :position [0 3], :layer 1, :shortcut :f7}
            {:hand :right,
             :finger :i,
             :position [0 3],
             :layer 3,
             :shortcut :clj/thread-last-backwards}
            {:hand :right, :finger :i, :position [0 2], :layer 0, :shortcut :g}
            {:hand :right,
             :finger :i,
             :position [0 2],
             :layer 2,
             :shortcut :home}
            {:hand :right, :finger :i, :position [2 0], :layer 0, :shortcut nil}
            {:hand :right, :finger :i, :position [0 -1], :layer 0, :shortcut :m}
            {:hand :right,
             :finger :i,
             :position [0 -1],
             :layer 2,
             :shortcut :cursive/sexp-left}
            {:hand :right,
             :finger :i,
             :position [0 -1],
             :layer 3,
             :shortcut :underscore}
            {:hand :right,
             :finger :i,
             :position [0 -1],
             :layer 4,
             :shortcut :plus}
            {:hand :right,
             :finger :i,
             :position [0 -1],
             :layer 5,
             :shortcut :semicolon}
            {:hand :right, :finger :i, :position [1 2], :layer 0, :shortcut :f}
            {:hand :right,
             :finger :i,
             :position [1 2],
             :layer 2,
             :shortcut :pageup}
            {:hand :right, :finger :i, :position [0 1], :layer 0, :shortcut :h}
            {:hand :right,
             :finger :i,
             :position [0 1],
             :layer 2,
             :shortcut :left}
            {:hand :right,
             :finger :i,
             :position [0 1],
             :layer 3,
             :shortcut :cursive/wrap-with-double-quotes}
            {:hand :right,
             :finger :i,
             :position [0 1],
             :layer 4,
             :shortcut :equals}
            {:hand :right,
             :finger :i,
             :position [0 1],
             :layer 5,
             :shortcut :double-quote}
            {:hand :right, :finger :m, :position [0 -1], :layer 0, :shortcut :w}
            {:hand :right,
             :finger :m,
             :position [0 -1],
             :layer 1,
             :shortcut :cursive/join-sexp}
            {:hand :right,
             :finger :m,
             :position [0 -1],
             :layer 2,
             :shortcut :cursive/sexp-down-right}
            {:hand :right,
             :finger :m,
             :position [0 -1],
             :layer 3,
             :shortcut :left-angle-brace}
            {:hand :right,
             :finger :m,
             :position [0 -1],
             :layer 5,
             :shortcut :comma}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 0,
             :shortcut :fun4}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 1,
             :shortcut :cursive/splice-sexp}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 2,
             :shortcut :cursive/sexp-up-left}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 3,
             :shortcut :left-round-brace}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 4,
             :shortcut :fun4}
            {:hand :right,
             :finger :m,
             :position [0 0],
             :layer 5,
             :shortcut :period}
            {:hand :right, :finger :m, :position [0 1], :layer 0, :shortcut :t}
            {:hand :right,
             :finger :m,
             :position [0 1],
             :layer 1,
             :shortcut :cursive/move-form-down}
            {:hand :right,
             :finger :m,
             :position [0 1],
             :layer 2,
             :shortcut :down}
            {:hand :right,
             :finger :m,
             :position [0 1],
             :layer 3,
             :shortcut :lbracket}
            {:hand :right,
             :finger :m,
             :position [0 1],
             :layer 5,
             :shortcut :quote}
            {:hand :right, :finger :m, :position [0 2], :layer 0, :shortcut :c}
            {:hand :right,
             :finger :m,
             :position [0 2],
             :layer 1,
             :shortcut :cursive/move-form-up}
            {:hand :right, :finger :m, :position [0 2], :layer 2, :shortcut :up}
            {:hand :right,
             :finger :m,
             :position [0 2],
             :layer 3,
             :shortcut :left-curly-brace}
            {:hand :right, :finger :m, :position [0 3], :layer 0, :shortcut :8}
            {:hand :right, :finger :m, :position [0 3], :layer 1, :shortcut :f8}
            {:hand :right,
             :finger :m,
             :position [0 3],
             :layer 3,
             :shortcut :clj/thread-first-backwards}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 0,
             :shortcut :fun5}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 1,
             :shortcut :cursive/barf-forward}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 2,
             :shortcut :cursive/sexp-up-right}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 3,
             :shortcut :right-round-brace}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 4,
             :shortcut :slash}
            {:hand :right,
             :finger :a,
             :position [0 0],
             :layer 5,
             :shortcut :fun5}
            {:hand :right,
             :finger :a,
             :position [-2 3],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :finger :a,
             :position [-1 0],
             :layer 0,
             :shortcut :enter}
            {:hand :right,
             :finger :a,
             :position [-1 0],
             :layer 3,
             :shortcut :cursive/wrap-with-round-braces}
            {:hand :right, :finger :a, :position [-1 3], :layer 0, :shortcut :0}
            {:hand :right,
             :finger :a,
             :position [-1 3],
             :layer 1,
             :shortcut :f10}
            {:hand :right,
             :finger :a,
             :position [-1 3],
             :layer 3,
             :shortcut :clj/thread-last}
            {:hand :right,
             :finger :a,
             :position [-1 2],
             :layer 0,
             :shortcut :backspace}
            {:hand :right,
             :finger :a,
             :position [-1 2],
             :layer 2,
             :shortcut :pagedown}
            {:hand :right,
             :finger :a,
             :position [-1 2],
             :layer 3,
             :shortcut :cursive/wrap-with-curly-braces}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 0,
             :shortcut :z}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 1,
             :shortcut :lat1}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 2,
             :shortcut :lat2}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 3,
             :shortcut :lat3}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 4,
             :shortcut :lat4}
            {:hand :right,
             :finger :a,
             :position [-1 -1],
             :layer 5,
             :shortcut :lat5}
            {:hand :right,
             :finger :a,
             :position [-2 1],
             :layer 0,
             :shortcut nil}
            {:hand :right,
             :finger :a,
             :position [-2 -1],
             :layer 0,
             :shortcut nil}
            {:hand :right, :finger :a, :position [0 3], :layer 0, :shortcut :9}
            {:hand :right, :finger :a, :position [0 3], :layer 1, :shortcut :f9}
            {:hand :right,
             :finger :a,
             :position [0 3],
             :layer 3,
             :shortcut :clj/thread-first}
            {:hand :right,
             :finger :a,
             :position [-2 2],
             :layer 0,
             :shortcut nil}
            {:hand :right, :finger :a, :position [0 2], :layer 0, :shortcut :r}
            {:hand :right,
             :finger :a,
             :position [0 2],
             :layer 1,
             :shortcut :cursive/raise-form}
            {:hand :right,
             :finger :a,
             :position [0 2],
             :layer 2,
             :shortcut :end}
            {:hand :right,
             :finger :a,
             :position [0 2],
             :layer 3,
             :shortcut :right-curly-brace}
            {:hand :right,
             :finger :a,
             :position [-1 1],
             :layer 0,
             :shortcut :escape}
            {:hand :right,
             :finger :a,
             :position [-1 1],
             :layer 2,
             :shortcut :next-word}
            {:hand :right,
             :finger :a,
             :position [-1 1],
             :layer 3,
             :shortcut :cursive/wrap-with-square-braces}
            {:hand :right, :finger :a, :position [0 -1], :layer 0, :shortcut :v}
            {:hand :right,
             :finger :a,
             :position [0 -1],
             :layer 2,
             :shortcut :cursive/sexp-right}
            {:hand :right,
             :finger :a,
             :position [0 -1],
             :layer 3,
             :shortcut :right-angle-brace}
            {:hand :right,
             :finger :a,
             :position [0 -1],
             :layer 4,
             :shortcut :backslash}
            {:hand :right,
             :finger :a,
             :position [-2 0],
             :layer 0,
             :shortcut nil}
            {:hand :right, :finger :a, :position [0 1], :layer 0, :shortcut :n}
            {:hand :right,
             :finger :a,
             :position [0 1],
             :layer 2,
             :shortcut :right}
            {:hand :right,
             :finger :a,
             :position [0 1],
             :layer 3,
             :shortcut :rbracket}
            {:hand :right,
             :finger :a,
             :position [0 1],
             :layer 4,
             :shortcut :question-mark}],
 :shortcuts {:left-curly-brace "{",
             :question-mark "?",
             :cursive/send-form-before-to-repl #{:shift :ctrl :b},
             :cursive/sexp-up-right #{:alt :n :ctrl},
             :cursive/split-sexp #{:shift :alt :s},
             :left-angle-brace "<",
             :cursive/slurp-forward #{:shift :0 :ctrl},
             :cursive/sexp-left #{:alt :ctrl :b},
             :cursive/move-form-down #{:shift :down :ctrl},
             :cursive/load-file-in-repl #{:shift :ctrl :l},
             :cursive/join-sexp #{:shift :alt :j},
             :cursive/close-round-brace-and-newline #{:shift :alt :0},
             :cursive/sexp-down-left #{:alt :ctrl :p},
             :right-curly-brace "}",
             :firmware/flashmode ("flashMode"),
             :cursive/splice-sexp #{:alt :s},
             :right-angle-brace ">",
             :tilde "~",
             :left-round-brace "(",
             :double-quote "\"",
             :colon ":",
             :cursive/raise-form #{:r :alt},
             :cursive/send-top-form-to-repl #{:shift :ctrl :t},
             :cursive/wrap-with-double-quotes #{:shift :alt :quote},
             :clj/thread-last "->>",
             :right-round-brace ")",
             :cursive/wrap-with-round-braces #{:shift :alt :9},
             :clj/thread-last-backwards "<<-",
             :previous-word #{:ctrl :left},
             :cursive/switch-repl-to-ns #{:shift :n :ctrl},
             :cursive/move-form-up #{:shift :ctrl :up},
             :cursive/sexp-up-left #{:alt :ctrl :u},
             :clj/thread-first "->",
             :cursive/extend-selection #{:w :ctrl},
             :plus "+",
             :cursive/sexp-right #{:alt :ctrl :f},
             :cursive/wrap-with-square-braces #{:alt :lbracket},
             :cursive/wrap-with-curly-braces #{:shift :alt :lbracket},
             :underscore "_",
             :cursive/shrink-selection #{:shift :w :ctrl},
             :next-word #{:ctrl :right},
             :clj/thread-first-backwards "<-",
             :cursive/kill-sexp #{:alt :ctrl :k},
             :cursive/barf-forward #{:shift :ctrl :rbrace},
             :cursive/sexp-down-right #{:alt :ctrl :d}},
 :kll-indexes {:left {:p {[0 0] :backspace,
                          [1 0] :delete,
                          [1 2] :lctrl,
                          [2 0] :end,
                          [2 1] :home,
                          [2 2] :lalt},
                      :i {[2 2] :function1,
                          [0 0] :v,
                          [1 0] :b,
                          [2 3] :escape,
                          [1 1] :g,
                          [1 3] :5,
                          [0 3] :4,
                          [0 2] :r,
                          [2 0] :function2,
                          [0 -1] :function5,
                          [1 2] :t,
                          [0 1] :f},
                      :m {[0 -1] :function4,
                          [0 0] :c,
                          [0 1] :d,
                          [0 2] :e,
                          [0 3] :3},
                      :a {[0 0] :x,
                          [-2 3] :equals,
                          [-1 0] :z,
                          [-1 3] :1,
                          [-1 2] :q,
                          [-1 -1] :backtick,
                          [-2 1] :tab,
                          [-2 -1] :lgui,
                          [0 3] :2,
                          [-2 2] :backslash,
                          [0 2] :w,
                          [-1 1] :a,
                          [0 -1] :function3,
                          [-2 0] :lshift,
                          [0 1] :s}},
               :right {:p {[0 0] :space,
                           [1 0] :enter,
                           [1 2] :rctrl,
                           [2 0] :pagedown,
                           [2 1] :pageup,
                           [2 2] :ralt},
                       :i {[2 2] :lbrace,
                           [0 0] :m,
                           [1 0] :n,
                           [2 3] :function6,
                           [1 1] :h,
                           [1 3] :6,
                           [0 3] :7,
                           [0 2] :u,
                           [2 0] :function7,
                           [0 -1] :left,
                           [1 2] :y,
                           [0 1] :j},
                       :m {[0 -1] :down,
                           [0 0] :comma,
                           [0 1] :k,
                           [0 2] :i,
                           [0 3] :8},
                       :a {[0 0] :period,
                           [-2 3] :minus,
                           [-1 0] :slash,
                           [-1 3] :0,
                           [-1 2] :p,
                           [-1 -1] :right,
                           [-2 1] :quote,
                           [-2 -1] :rgui,
                           [0 3] :9,
                           [-2 2] :rbrace,
                           [0 2] :o,
                           [-1 1] :semicolon,
                           [0 -1] :up,
                           [-2 0] :rshift,
                           [0 1] :l}}},
 :xf [{:hand :left,
       :finger :p,
       :position [0 0],
       :layer 0,
       :shortcut :lctrl,
       :kll-index :backspace,
       :kll-value "U\"LCTRL\";",
       :line-comment "left p [0 0]"}
      {:hand :left,
       :finger :p,
       :position [1 0],
       :layer 0,
       :shortcut :lalt,
       :kll-index :delete,
       :kll-value "U\"LALT\";",
       :line-comment "left p [1 0]"}
      {:hand :left,
       :finger :p,
       :position [1 2],
       :layer 0,
       :shortcut :lshift,
       :kll-index :lctrl,
       :kll-value "U\"LSHIFT\";",
       :line-comment "left p [1 2]"}
      {:hand :left,
       :finger :p,
       :position [2 0],
       :layer 0,
       :shortcut :escape,
       :kll-index :end,
       :kll-value "U\"ESCAPE\";",
       :line-comment "left p [2 0]"}
      {:hand :left,
       :finger :p,
       :position [2 1],
       :layer 0,
       :shortcut :lgui,
       :kll-index :home,
       :kll-value "U\"LGUI\";",
       :line-comment "left p [2 1]"}
      {:hand :left,
       :finger :p,
       :position [2 1],
       :layer 1,
       :shortcut :app,
       :kll-index :home,
       :kll-value "U\"APP\";",
       :line-comment "left p [2 1]"}
      {:hand :left,
       :finger :p,
       :position [2 2],
       :layer 0,
       :shortcut :space,
       :kll-index :lalt,
       :kll-value "U\"SPACE\";",
       :line-comment "left p [2 2]"}
      {:hand :left,
       :finger :i,
       :position [2 2],
       :layer 0,
       :shortcut nil,
       :kll-index :function1,
       :kll-value "None;",
       :line-comment "left i [2 2]"}
      {:hand :left,
       :finger :i,
       :position [0 0],
       :layer 0,
       :shortcut :fun1,
       :kll-index :v,
       :kll-value "U\"FUN1\";",
       :line-comment "left i [0 0]"}
      {:hand :left,
       :finger :i,
       :position [0 0],
       :layer 2,
       :shortcut :cursive/send-top-form-to-repl,
       :kll-index :v,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"T\";",
       :line-comment "left i [0 0]"}
      {:hand :left,
       :finger :i,
       :position [1 0],
       :layer 0,
       :shortcut :x,
       :kll-index :b,
       :kll-value "U\"X\";",
       :line-comment "left i [1 0]"}
      {:hand :left,
       :finger :i,
       :position [2 3],
       :layer 0,
       :shortcut nil,
       :kll-index :escape,
       :kll-value "None;",
       :line-comment "left i [2 3]"}
      {:hand :left,
       :finger :i,
       :position [2 3],
       :layer 1,
       :shortcut :firmware/flashmode,
       :kll-index :escape,
       :kll-value "flashMode();",
       :line-comment "left i [2 3]"}
      {:hand :left,
       :finger :i,
       :position [1 1],
       :layer 0,
       :shortcut :i,
       :kll-index :g,
       :kll-value "U\"I\";",
       :line-comment "left i [1 1]"}
      {:hand :left,
       :finger :i,
       :position [1 3],
       :layer 0,
       :shortcut :5,
       :kll-index :5,
       :kll-value "U\"5\";",
       :line-comment "left i [1 3]"}
      {:hand :left,
       :finger :i,
       :position [1 3],
       :layer 1,
       :shortcut :f5,
       :kll-index :5,
       :kll-value "U\"F5\";",
       :line-comment "left i [1 3]"}
      {:hand :left,
       :finger :i,
       :position [1 3],
       :layer 3,
       :shortcut :f5,
       :kll-index :5,
       :kll-value "U\"F5\";",
       :line-comment "left i [1 3]"}
      {:hand :left,
       :finger :i,
       :position [1 3],
       :layer 4,
       :shortcut :f15,
       :kll-index :5,
       :kll-value "U\"F15\";",
       :line-comment "left i [1 3]"}
      {:hand :left,
       :finger :i,
       :position [0 3],
       :layer 0,
       :shortcut :4,
       :kll-index :4,
       :kll-value "U\"4\";",
       :line-comment "left i [0 3]"}
      {:hand :left,
       :finger :i,
       :position [0 3],
       :layer 1,
       :shortcut :f4,
       :kll-index :4,
       :kll-value "U\"F4\";",
       :line-comment "left i [0 3]"}
      {:hand :left,
       :finger :i,
       :position [0 3],
       :layer 3,
       :shortcut :f4,
       :kll-index :4,
       :kll-value "U\"F4\";",
       :line-comment "left i [0 3]"}
      {:hand :left,
       :finger :i,
       :position [0 3],
       :layer 4,
       :shortcut :f14,
       :kll-index :4,
       :kll-value "U\"F14\";",
       :line-comment "left i [0 3]"}
      {:hand :left,
       :finger :i,
       :position [0 2],
       :layer 0,
       :shortcut :p,
       :kll-index :r,
       :kll-value "U\"P\";",
       :line-comment "left i [0 2]"}
      {:hand :left,
       :finger :i,
       :position [2 0],
       :layer 0,
       :shortcut nil,
       :kll-index :function2,
       :kll-value "None;",
       :line-comment "left i [2 0]"}
      {:hand :left,
       :finger :i,
       :position [0 -1],
       :layer 0,
       :shortcut :s,
       :kll-index :function5,
       :kll-value "U\"S\";",
       :line-comment "left i [0 -1]"}
      {:hand :left,
       :finger :i,
       :position [0 -1],
       :layer 2,
       :shortcut :cursive/split-sexp,
       :kll-index :function5,
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"S\";",
       :line-comment "left i [0 -1]"}
      {:hand :left,
       :finger :i,
       :position [1 2],
       :layer 0,
       :shortcut :y,
       :kll-index :t,
       :kll-value "U\"Y\";",
       :line-comment "left i [1 2]"}
      {:hand :left,
       :finger :i,
       :position [0 1],
       :layer 0,
       :shortcut :u,
       :kll-index :f,
       :kll-value "U\"U\";",
       :line-comment "left i [0 1]"}
      {:hand :left,
       :finger :m,
       :position [0 -1],
       :layer 0,
       :shortcut :k,
       :kll-index :function4,
       :kll-value "U\"K\";",
       :line-comment "left m [0 -1]"}
      {:hand :left,
       :finger :m,
       :position [0 -1],
       :layer 2,
       :shortcut :cursive/kill-sexp,
       :kll-index :function4,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"K\";",
       :line-comment "left m [0 -1]"}
      {:hand :left,
       :finger :m,
       :position [0 0],
       :layer 0,
       :shortcut :fun2,
       :kll-index :c,
       :kll-value "U\"FUN2\";",
       :line-comment "left m [0 0]"}
      {:hand :left,
       :finger :m,
       :position [0 0],
       :layer 1,
       :shortcut :cursive/send-top-form-to-repl,
       :kll-index :c,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"T\";",
       :line-comment "left m [0 0]"}
      {:hand :left,
       :finger :m,
       :position [0 1],
       :layer 0,
       :shortcut :e,
       :kll-index :d,
       :kll-value "U\"E\";",
       :line-comment "left m [0 1]"}
      {:hand :left,
       :finger :m,
       :position [0 1],
       :layer 1,
       :shortcut :cursive/extend-selection,
       :kll-index :d,
       :kll-value "U\"W\" + U\"CTRL\";",
       :line-comment "left m [0 1]"}
      {:hand :left,
       :finger :m,
       :position [0 2],
       :layer 0,
       :shortcut :a,
       :kll-index :e,
       :kll-value "U\"A\";",
       :line-comment "left m [0 2]"}
      {:hand :left,
       :finger :m,
       :position [0 2],
       :layer 1,
       :shortcut :cursive/switch-repl-to-ns,
       :kll-index :e,
       :kll-value "U\"SHIFT\" + U\"N\" + U\"CTRL\";",
       :line-comment "left m [0 2]"}
      {:hand :left,
       :finger :m,
       :position [0 3],
       :layer 0,
       :shortcut :3,
       :kll-index :3,
       :kll-value "U\"3\";",
       :line-comment "left m [0 3]"}
      {:hand :left,
       :finger :m,
       :position [0 3],
       :layer 1,
       :shortcut :f3,
       :kll-index :3,
       :kll-value "U\"F3\";",
       :line-comment "left m [0 3]"}
      {:hand :left,
       :finger :m,
       :position [0 3],
       :layer 3,
       :shortcut :f3,
       :kll-index :3,
       :kll-value "U\"F3\";",
       :line-comment "left m [0 3]"}
      {:hand :left,
       :finger :m,
       :position [0 3],
       :layer 4,
       :shortcut :f13,
       :kll-index :3,
       :kll-value "U\"F13\";",
       :line-comment "left m [0 3]"}
      {:hand :left,
       :finger :a,
       :position [0 0],
       :layer 0,
       :shortcut :j,
       :kll-index :x,
       :kll-value "U\"J\";",
       :line-comment "left a [0 0]"}
      {:hand :left,
       :finger :a,
       :position [0 0],
       :layer 1,
       :shortcut :cursive/send-form-before-to-repl,
       :kll-index :x,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"B\";",
       :line-comment "left a [0 0]"}
      {:hand :left,
       :finger :a,
       :position [-2 3],
       :layer 0,
       :shortcut nil,
       :kll-index :equals,
       :kll-value "None;",
       :line-comment "left a [-2 3]"}
      {:hand :left,
       :finger :a,
       :position [-1 0],
       :layer 0,
       :shortcut :backslash,
       :kll-index :z,
       :kll-value "U\"BACKSLASH\";",
       :line-comment "left a [-1 0]"}
      {:hand :left,
       :finger :a,
       :position [-1 3],
       :layer 0,
       :shortcut :1,
       :kll-index :1,
       :kll-value "U\"1\";",
       :line-comment "left a [-1 3]"}
      {:hand :left,
       :finger :a,
       :position [-1 3],
       :layer 1,
       :shortcut :f1,
       :kll-index :1,
       :kll-value "U\"F1\";",
       :line-comment "left a [-1 3]"}
      {:hand :left,
       :finger :a,
       :position [-1 3],
       :layer 3,
       :shortcut :f1,
       :kll-index :1,
       :kll-value "U\"F1\";",
       :line-comment "left a [-1 3]"}
      {:hand :left,
       :finger :a,
       :position [-1 3],
       :layer 4,
       :shortcut :f12,
       :kll-index :1,
       :kll-value "U\"F12\";",
       :line-comment "left a [-1 3]"}
      {:hand :left,
       :finger :a,
       :position [-1 2],
       :layer 0,
       :shortcut :tab,
       :kll-index :q,
       :kll-value "U\"TAB\";",
       :line-comment "left a [-1 2]"}
      {:hand :left,
       :finger :a,
       :position [-1 -1],
       :layer 0,
       :shortcut nil,
       :kll-index :backtick,
       :kll-value "None;",
       :line-comment "left a [-1 -1]"}
      {:hand :left,
       :finger :a,
       :position [-2 1],
       :layer 0,
       :shortcut nil,
       :kll-index :tab,
       :kll-value "None;",
       :line-comment "left a [-2 1]"}
      {:hand :left,
       :finger :a,
       :position [-2 -1],
       :layer 0,
       :shortcut nil,
       :kll-index :lgui,
       :kll-value "None;",
       :line-comment "left a [-2 -1]"}
      {:hand :left,
       :finger :a,
       :position [0 3],
       :layer 0,
       :shortcut :2,
       :kll-index :2,
       :kll-value "U\"2\";",
       :line-comment "left a [0 3]"}
      {:hand :left,
       :finger :a,
       :position [0 3],
       :layer 1,
       :shortcut :f2,
       :kll-index :2,
       :kll-value "U\"F2\";",
       :line-comment "left a [0 3]"}
      {:hand :left,
       :finger :a,
       :position [0 3],
       :layer 3,
       :shortcut :f2,
       :kll-index :2,
       :kll-value "U\"F2\";",
       :line-comment "left a [0 3]"}
      {:hand :left,
       :finger :a,
       :position [0 3],
       :layer 4,
       :shortcut :f12,
       :kll-index :2,
       :kll-value "U\"F12\";",
       :line-comment "left a [0 3]"}
      {:hand :left,
       :finger :a,
       :position [-2 2],
       :layer 0,
       :shortcut nil,
       :kll-index :backslash,
       :kll-value "None;",
       :line-comment "left a [-2 2]"}
      {:hand :left,
       :finger :a,
       :position [0 2],
       :layer 0,
       :shortcut :l,
       :kll-index :w,
       :kll-value "U\"L\";",
       :line-comment "left a [0 2]"}
      {:hand :left,
       :finger :a,
       :position [0 2],
       :layer 1,
       :shortcut :cursive/load-file-in-repl,
       :kll-index :w,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"L\";",
       :line-comment "left a [0 2]"}
      {:hand :left,
       :finger :a,
       :position [-1 1],
       :layer 0,
       :shortcut :delete,
       :kll-index :a,
       :kll-value "U\"DELETE\";",
       :line-comment "left a [-1 1]"}
      {:hand :left,
       :finger :a,
       :position [0 -1],
       :layer 0,
       :shortcut :q,
       :kll-index :function3,
       :kll-value "U\"Q\";",
       :line-comment "left a [0 -1]"}
      {:hand :left,
       :finger :a,
       :position [-2 0],
       :layer 0,
       :shortcut nil,
       :kll-index :lshift,
       :kll-value "None;",
       :line-comment "left a [-2 0]"}
      {:hand :left,
       :finger :a,
       :position [0 1],
       :layer 0,
       :shortcut :o,
       :kll-index :s,
       :kll-value "U\"O\";",
       :line-comment "left a [0 1]"}
      {:hand :left,
       :finger :a,
       :position [0 1],
       :layer 1,
       :shortcut :cursive/shrink-selection,
       :kll-index :s,
       :kll-value "U\"SHIFT\" + U\"W\" + U\"CTRL\";",
       :line-comment "left a [0 1]"}
      {:hand :right,
       :finger :p,
       :position [0 0],
       :layer 0,
       :shortcut :space,
       :kll-index :space,
       :kll-value "U\"SPACE\";",
       :line-comment "right p [0 0]"}
      {:hand :right,
       :finger :p,
       :position [1 0],
       :layer 0,
       :shortcut :rshift,
       :kll-index :enter,
       :kll-value "U\"RSHIFT\";",
       :line-comment "right p [1 0]"}
      {:hand :right,
       :finger :p,
       :position [1 2],
       :layer 0,
       :shortcut :ralt,
       :kll-index :rctrl,
       :kll-value "U\"RALT\";",
       :line-comment "right p [1 2]"}
      {:hand :right,
       :finger :p,
       :position [2 0],
       :layer 0,
       :shortcut :escape,
       :kll-index :pagedown,
       :kll-value "U\"ESCAPE\";",
       :line-comment "right p [2 0]"}
      {:hand :right,
       :finger :p,
       :position [2 1],
       :layer 0,
       :shortcut :rgui,
       :kll-index :pageup,
       :kll-value "U\"RGUI\";",
       :line-comment "right p [2 1]"}
      {:hand :right,
       :finger :p,
       :position [2 1],
       :layer 1,
       :shortcut :app,
       :kll-index :pageup,
       :kll-value "U\"APP\";",
       :line-comment "right p [2 1]"}
      {:hand :right,
       :finger :p,
       :position [2 2],
       :layer 0,
       :shortcut :ralt,
       :kll-index :ralt,
       :kll-value "U\"RALT\";",
       :line-comment "right p [2 2]"}
      {:hand :right,
       :finger :i,
       :position [2 2],
       :layer 0,
       :shortcut nil,
       :kll-index :lbrace,
       :kll-value "None;",
       :line-comment "right i [2 2]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 0,
       :shortcut :fun3,
       :kll-index :m,
       :kll-value "U\"FUN3\";",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 1,
       :shortcut :cursive/slurp-forward,
       :kll-index :m,
       :kll-value "U\"SHIFT\" + U\"0\" + U\"CTRL\";",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 2,
       :shortcut :cursive/sexp-down-left,
       :kll-index :m,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"P\";",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 3,
       :shortcut :fun3,
       :kll-index :m,
       :kll-value "U\"FUN3\";",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 4,
       :shortcut :minus,
       :kll-index :m,
       :kll-value "U\"MINUS\";",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [0 0],
       :layer 5,
       :shortcut :colon,
       :kll-index :m,
       :kll-value "':';",
       :line-comment "right i [0 0]"}
      {:hand :right,
       :finger :i,
       :position [1 0],
       :layer 0,
       :shortcut :b,
       :kll-index :n,
       :kll-value "U\"B\";",
       :line-comment "right i [1 0]"}
      {:hand :right,
       :finger :i,
       :position [1 0],
       :layer 5,
       :shortcut :tilde,
       :kll-index :n,
       :kll-value "'~';",
       :line-comment "right i [1 0]"}
      {:hand :right,
       :finger :i,
       :position [2 3],
       :layer 0,
       :shortcut nil,
       :kll-index :function6,
       :kll-value "None;",
       :line-comment "right i [2 3]"}
      {:hand :right,
       :finger :i,
       :position [2 3],
       :layer 3,
       :shortcut :firmware/flashmode,
       :kll-index :function6,
       :kll-value "flashMode();",
       :line-comment "right i [2 3]"}
      {:hand :right,
       :finger :i,
       :position [1 1],
       :layer 0,
       :shortcut :d,
       :kll-index :h,
       :kll-value "U\"D\";",
       :line-comment "right i [1 1]"}
      {:hand :right,
       :finger :i,
       :position [1 1],
       :layer 2,
       :shortcut :previous-word,
       :kll-index :h,
       :kll-value "U\"CTRL\" + U\"LEFT\";",
       :line-comment "right i [1 1]"}
      {:hand :right,
       :finger :i,
       :position [1 1],
       :layer 5,
       :shortcut :backtick,
       :kll-index :h,
       :kll-value "U\"BACKTICK\";",
       :line-comment "right i [1 1]"}
      {:hand :right,
       :finger :i,
       :position [1 3],
       :layer 0,
       :shortcut :6,
       :kll-index :6,
       :kll-value "U\"6\";",
       :line-comment "right i [1 3]"}
      {:hand :right,
       :finger :i,
       :position [1 3],
       :layer 1,
       :shortcut :f6,
       :kll-index :6,
       :kll-value "U\"F6\";",
       :line-comment "right i [1 3]"}
      {:hand :right,
       :finger :i,
       :position [0 3],
       :layer 0,
       :shortcut :7,
       :kll-index :7,
       :kll-value "U\"7\";",
       :line-comment "right i [0 3]"}
      {:hand :right,
       :finger :i,
       :position [0 3],
       :layer 1,
       :shortcut :f7,
       :kll-index :7,
       :kll-value "U\"F7\";",
       :line-comment "right i [0 3]"}
      {:hand :right,
       :finger :i,
       :position [0 3],
       :layer 3,
       :shortcut :clj/thread-last-backwards,
       :kll-index :7,
       :kll-value "'<<-';",
       :line-comment "right i [0 3]"}
      {:hand :right,
       :finger :i,
       :position [0 2],
       :layer 0,
       :shortcut :g,
       :kll-index :u,
       :kll-value "U\"G\";",
       :line-comment "right i [0 2]"}
      {:hand :right,
       :finger :i,
       :position [0 2],
       :layer 2,
       :shortcut :home,
       :kll-index :u,
       :kll-value "U\"HOME\";",
       :line-comment "right i [0 2]"}
      {:hand :right,
       :finger :i,
       :position [2 0],
       :layer 0,
       :shortcut nil,
       :kll-index :function7,
       :kll-value "None;",
       :line-comment "right i [2 0]"}
      {:hand :right,
       :finger :i,
       :position [0 -1],
       :layer 0,
       :shortcut :m,
       :kll-index :left,
       :kll-value "U\"M\";",
       :line-comment "right i [0 -1]"}
      {:hand :right,
       :finger :i,
       :position [0 -1],
       :layer 2,
       :shortcut :cursive/sexp-left,
       :kll-index :left,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"B\";",
       :line-comment "right i [0 -1]"}
      {:hand :right,
       :finger :i,
       :position [0 -1],
       :layer 3,
       :shortcut :underscore,
       :kll-index :left,
       :kll-value "'_';",
       :line-comment "right i [0 -1]"}
      {:hand :right,
       :finger :i,
       :position [0 -1],
       :layer 4,
       :shortcut :plus,
       :kll-index :left,
       :kll-value "'+';",
       :line-comment "right i [0 -1]"}
      {:hand :right,
       :finger :i,
       :position [0 -1],
       :layer 5,
       :shortcut :semicolon,
       :kll-index :left,
       :kll-value "U\"SEMICOLON\";",
       :line-comment "right i [0 -1]"}
      {:hand :right,
       :finger :i,
       :position [1 2],
       :layer 0,
       :shortcut :f,
       :kll-index :y,
       :kll-value "U\"F\";",
       :line-comment "right i [1 2]"}
      {:hand :right,
       :finger :i,
       :position [1 2],
       :layer 2,
       :shortcut :pageup,
       :kll-index :y,
       :kll-value "U\"PAGEUP\";",
       :line-comment "right i [1 2]"}
      {:hand :right,
       :finger :i,
       :position [0 1],
       :layer 0,
       :shortcut :h,
       :kll-index :j,
       :kll-value "U\"H\";",
       :line-comment "right i [0 1]"}
      {:hand :right,
       :finger :i,
       :position [0 1],
       :layer 2,
       :shortcut :left,
       :kll-index :j,
       :kll-value "U\"LEFT\";",
       :line-comment "right i [0 1]"}
      {:hand :right,
       :finger :i,
       :position [0 1],
       :layer 3,
       :shortcut :cursive/wrap-with-double-quotes,
       :kll-index :j,
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"QUOTE\";",
       :line-comment "right i [0 1]"}
      {:hand :right,
       :finger :i,
       :position [0 1],
       :layer 4,
       :shortcut :equals,
       :kll-index :j,
       :kll-value "U\"EQUALS\";",
       :line-comment "right i [0 1]"}
      {:hand :right,
       :finger :i,
       :position [0 1],
       :layer 5,
       :shortcut :double-quote,
       :kll-index :j,
       :kll-value "'\"';",
       :line-comment "right i [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 -1],
       :layer 0,
       :shortcut :w,
       :kll-index :down,
       :kll-value "U\"W\";",
       :line-comment "right m [0 -1]"}
      {:hand :right,
       :finger :m,
       :position [0 -1],
       :layer 1,
       :shortcut :cursive/join-sexp,
       :kll-index :down,
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"J\";",
       :line-comment "right m [0 -1]"}
      {:hand :right,
       :finger :m,
       :position [0 -1],
       :layer 2,
       :shortcut :cursive/sexp-down-right,
       :kll-index :down,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"D\";",
       :line-comment "right m [0 -1]"}
      {:hand :right,
       :finger :m,
       :position [0 -1],
       :layer 3,
       :shortcut :left-angle-brace,
       :kll-index :down,
       :kll-value "'<';",
       :line-comment "right m [0 -1]"}
      {:hand :right,
       :finger :m,
       :position [0 -1],
       :layer 5,
       :shortcut :comma,
       :kll-index :down,
       :kll-value "U\"COMMA\";",
       :line-comment "right m [0 -1]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 0,
       :shortcut :fun4,
       :kll-index :comma,
       :kll-value "U\"FUN4\";",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 1,
       :shortcut :cursive/splice-sexp,
       :kll-index :comma,
       :kll-value "U\"ALT\" + U\"S\";",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 2,
       :shortcut :cursive/sexp-up-left,
       :kll-index :comma,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"U\";",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 3,
       :shortcut :left-round-brace,
       :kll-index :comma,
       :kll-value "'(';",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 4,
       :shortcut :fun4,
       :kll-index :comma,
       :kll-value "U\"FUN4\";",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 0],
       :layer 5,
       :shortcut :period,
       :kll-index :comma,
       :kll-value "U\"PERIOD\";",
       :line-comment "right m [0 0]"}
      {:hand :right,
       :finger :m,
       :position [0 1],
       :layer 0,
       :shortcut :t,
       :kll-index :k,
       :kll-value "U\"T\";",
       :line-comment "right m [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 1],
       :layer 1,
       :shortcut :cursive/move-form-down,
       :kll-index :k,
       :kll-value "U\"SHIFT\" + U\"DOWN\" + U\"CTRL\";",
       :line-comment "right m [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 1],
       :layer 2,
       :shortcut :down,
       :kll-index :k,
       :kll-value "U\"DOWN\";",
       :line-comment "right m [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 1],
       :layer 3,
       :shortcut :lbracket,
       :kll-index :k,
       :kll-value "U\"LBRACKET\";",
       :line-comment "right m [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 1],
       :layer 5,
       :shortcut :quote,
       :kll-index :k,
       :kll-value "U\"QUOTE\";",
       :line-comment "right m [0 1]"}
      {:hand :right,
       :finger :m,
       :position [0 2],
       :layer 0,
       :shortcut :c,
       :kll-index :i,
       :kll-value "U\"C\";",
       :line-comment "right m [0 2]"}
      {:hand :right,
       :finger :m,
       :position [0 2],
       :layer 1,
       :shortcut :cursive/move-form-up,
       :kll-index :i,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"UP\";",
       :line-comment "right m [0 2]"}
      {:hand :right,
       :finger :m,
       :position [0 2],
       :layer 2,
       :shortcut :up,
       :kll-index :i,
       :kll-value "U\"UP\";",
       :line-comment "right m [0 2]"}
      {:hand :right,
       :finger :m,
       :position [0 2],
       :layer 3,
       :shortcut :left-curly-brace,
       :kll-index :i,
       :kll-value "'{';",
       :line-comment "right m [0 2]"}
      {:hand :right,
       :finger :m,
       :position [0 3],
       :layer 0,
       :shortcut :8,
       :kll-index :8,
       :kll-value "U\"8\";",
       :line-comment "right m [0 3]"}
      {:hand :right,
       :finger :m,
       :position [0 3],
       :layer 1,
       :shortcut :f8,
       :kll-index :8,
       :kll-value "U\"F8\";",
       :line-comment "right m [0 3]"}
      {:hand :right,
       :finger :m,
       :position [0 3],
       :layer 3,
       :shortcut :clj/thread-first-backwards,
       :kll-index :8,
       :kll-value "'<-';",
       :line-comment "right m [0 3]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 0,
       :shortcut :fun5,
       :kll-index :period,
       :kll-value "U\"FUN5\";",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 1,
       :shortcut :cursive/barf-forward,
       :kll-index :period,
       :kll-value "U\"SHIFT\" + U\"CTRL\" + U\"RBRACE\";",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 2,
       :shortcut :cursive/sexp-up-right,
       :kll-index :period,
       :kll-value "U\"ALT\" + U\"N\" + U\"CTRL\";",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 3,
       :shortcut :right-round-brace,
       :kll-index :period,
       :kll-value "')';",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 4,
       :shortcut :slash,
       :kll-index :period,
       :kll-value "U\"SLASH\";",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [0 0],
       :layer 5,
       :shortcut :fun5,
       :kll-index :period,
       :kll-value "U\"FUN5\";",
       :line-comment "right a [0 0]"}
      {:hand :right,
       :finger :a,
       :position [-2 3],
       :layer 0,
       :shortcut nil,
       :kll-index :minus,
       :kll-value "None;",
       :line-comment "right a [-2 3]"}
      {:hand :right,
       :finger :a,
       :position [-1 0],
       :layer 0,
       :shortcut :enter,
       :kll-index :slash,
       :kll-value "U\"ENTER\";",
       :line-comment "right a [-1 0]"}
      {:hand :right,
       :finger :a,
       :position [-1 0],
       :layer 3,
       :shortcut :cursive/wrap-with-round-braces,
       :kll-index :slash,
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"9\";",
       :line-comment "right a [-1 0]"}
      {:hand :right,
       :finger :a,
       :position [-1 3],
       :layer 0,
       :shortcut :0,
       :kll-index :0,
       :kll-value "U\"0\";",
       :line-comment "right a [-1 3]"}
      {:hand :right,
       :finger :a,
       :position [-1 3],
       :layer 1,
       :shortcut :f10,
       :kll-index :0,
       :kll-value "U\"F10\";",
       :line-comment "right a [-1 3]"}
      {:hand :right,
       :finger :a,
       :position [-1 3],
       :layer 3,
       :shortcut :clj/thread-last,
       :kll-index :0,
       :kll-value "'->>';",
       :line-comment "right a [-1 3]"}
      {:hand :right,
       :finger :a,
       :position [-1 2],
       :layer 0,
       :shortcut :backspace,
       :kll-index :p,
       :kll-value "U\"BACKSPACE\";",
       :line-comment "right a [-1 2]"}
      {:hand :right,
       :finger :a,
       :position [-1 2],
       :layer 2,
       :shortcut :pagedown,
       :kll-index :p,
       :kll-value "U\"PAGEDOWN\";",
       :line-comment "right a [-1 2]"}
      {:hand :right,
       :finger :a,
       :position [-1 2],
       :layer 3,
       :shortcut :cursive/wrap-with-curly-braces,
       :kll-index :p,
       :kll-value "U\"SHIFT\" + U\"ALT\" + U\"LBRACKET\";",
       :line-comment "right a [-1 2]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 0,
       :shortcut :z,
       :kll-index :right,
       :kll-value "U\"Z\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 1,
       :shortcut :lat1,
       :kll-index :right,
       :kll-value "U\"LAT1\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 2,
       :shortcut :lat2,
       :kll-index :right,
       :kll-value "U\"LAT2\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 3,
       :shortcut :lat3,
       :kll-index :right,
       :kll-value "U\"LAT3\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 4,
       :shortcut :lat4,
       :kll-index :right,
       :kll-value "U\"LAT4\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-1 -1],
       :layer 5,
       :shortcut :lat5,
       :kll-index :right,
       :kll-value "U\"LAT5\";",
       :line-comment "right a [-1 -1]"}
      {:hand :right,
       :finger :a,
       :position [-2 1],
       :layer 0,
       :shortcut nil,
       :kll-index :quote,
       :kll-value "None;",
       :line-comment "right a [-2 1]"}
      {:hand :right,
       :finger :a,
       :position [-2 -1],
       :layer 0,
       :shortcut nil,
       :kll-index :rgui,
       :kll-value "None;",
       :line-comment "right a [-2 -1]"}
      {:hand :right,
       :finger :a,
       :position [0 3],
       :layer 0,
       :shortcut :9,
       :kll-index :9,
       :kll-value "U\"9\";",
       :line-comment "right a [0 3]"}
      {:hand :right,
       :finger :a,
       :position [0 3],
       :layer 1,
       :shortcut :f9,
       :kll-index :9,
       :kll-value "U\"F9\";",
       :line-comment "right a [0 3]"}
      {:hand :right,
       :finger :a,
       :position [0 3],
       :layer 3,
       :shortcut :clj/thread-first,
       :kll-index :9,
       :kll-value "'->';",
       :line-comment "right a [0 3]"}
      {:hand :right,
       :finger :a,
       :position [-2 2],
       :layer 0,
       :shortcut nil,
       :kll-index :rbrace,
       :kll-value "None;",
       :line-comment "right a [-2 2]"}
      {:hand :right,
       :finger :a,
       :position [0 2],
       :layer 0,
       :shortcut :r,
       :kll-index :o,
       :kll-value "U\"R\";",
       :line-comment "right a [0 2]"}
      {:hand :right,
       :finger :a,
       :position [0 2],
       :layer 1,
       :shortcut :cursive/raise-form,
       :kll-index :o,
       :kll-value "U\"R\" + U\"ALT\";",
       :line-comment "right a [0 2]"}
      {:hand :right,
       :finger :a,
       :position [0 2],
       :layer 2,
       :shortcut :end,
       :kll-index :o,
       :kll-value "U\"END\";",
       :line-comment "right a [0 2]"}
      {:hand :right,
       :finger :a,
       :position [0 2],
       :layer 3,
       :shortcut :right-curly-brace,
       :kll-index :o,
       :kll-value "'}';",
       :line-comment "right a [0 2]"}
      {:hand :right,
       :finger :a,
       :position [-1 1],
       :layer 0,
       :shortcut :escape,
       :kll-index :semicolon,
       :kll-value "U\"ESCAPE\";",
       :line-comment "right a [-1 1]"}
      {:hand :right,
       :finger :a,
       :position [-1 1],
       :layer 2,
       :shortcut :next-word,
       :kll-index :semicolon,
       :kll-value "U\"CTRL\" + U\"RIGHT\";",
       :line-comment "right a [-1 1]"}
      {:hand :right,
       :finger :a,
       :position [-1 1],
       :layer 3,
       :shortcut :cursive/wrap-with-square-braces,
       :kll-index :semicolon,
       :kll-value "U\"ALT\" + U\"LBRACKET\";",
       :line-comment "right a [-1 1]"}
      {:hand :right,
       :finger :a,
       :position [0 -1],
       :layer 0,
       :shortcut :v,
       :kll-index :up,
       :kll-value "U\"V\";",
       :line-comment "right a [0 -1]"}
      {:hand :right,
       :finger :a,
       :position [0 -1],
       :layer 2,
       :shortcut :cursive/sexp-right,
       :kll-index :up,
       :kll-value "U\"ALT\" + U\"CTRL\" + U\"F\";",
       :line-comment "right a [0 -1]"}
      {:hand :right,
       :finger :a,
       :position [0 -1],
       :layer 3,
       :shortcut :right-angle-brace,
       :kll-index :up,
       :kll-value "'>';",
       :line-comment "right a [0 -1]"}
      {:hand :right,
       :finger :a,
       :position [0 -1],
       :layer 4,
       :shortcut :backslash,
       :kll-index :up,
       :kll-value "U\"BACKSLASH\";",
       :line-comment "right a [0 -1]"}
      {:hand :right,
       :finger :a,
       :position [-2 0],
       :layer 0,
       :shortcut nil,
       :kll-index :rshift,
       :kll-value "None;",
       :line-comment "right a [-2 0]"}
      {:hand :right,
       :finger :a,
       :position [0 1],
       :layer 0,
       :shortcut :n,
       :kll-index :l,
       :kll-value "U\"N\";",
       :line-comment "right a [0 1]"}
      {:hand :right,
       :finger :a,
       :position [0 1],
       :layer 2,
       :shortcut :right,
       :kll-index :l,
       :kll-value "U\"RIGHT\";",
       :line-comment "right a [0 1]"}
      {:hand :right,
       :finger :a,
       :position [0 1],
       :layer 3,
       :shortcut :rbracket,
       :kll-index :l,
       :kll-value "U\"RBRACKET\";",
       :line-comment "right a [0 1]"}
      {:hand :right,
       :finger :a,
       :position [0 1],
       :layer 4,
       :shortcut :question-mark,
       :kll-index :l,
       :kll-value "'?';",
       :line-comment "right a [0 1]"}]}
